class SongsModel {
  final bool isSecondChorus;
  final bool isFirstChorus;
  final String musicTrackPath;
  final String page;
  final String title;
  final List<String> lyrics;
  final SongsCategory songsCategory;

  // final List<String> chorus;

  SongsModel(
    this.title,
    this.page,
    this.lyrics,
    this.songsCategory, {
    this.musicTrackPath = '',
    this.isSecondChorus = false,
    this.isFirstChorus = false,
  });
}

final List<SongsModel> songs = [
  SongsModel(
    'NOVO HINO DA CHEON IL GUK',
    '0',
    [
      'O puro amor irá florir com novas de esperança,\nNovo mundo de liberdade, terra e céu rejubilam\nReino de paz traz esperança, prosperidade e amor\n Brilhando eternamente na Cheon II Guk, na terra de Deus.\n',
      'Brilha o lírio à luz do Céu, esplendor divinal\nNuma vida de bondade puro amor nos ilumina\nProsperando no amor de Deus, felizes para sempre\nBrilhando eternamente na Cheon II Guk, na terra de Deus.\n',
      'A nova vida bela e pura reflete o ideal\nComo o grou nos altos montes Deus já Se revelou\nCéu e terra rejubilam na calma da manhã\nBrilhando eternamente na Cheon II Guk, na terra de Deus.\n',
      'Os Verdadeiros Pais nos dão o Verdadeiro Amor\nIdeal tão ansiado é o Reino de Deus\nA bandeira da Cheon Il Guk erguida firmemente\nBrilhando eternamente na Cheon II Guk, na terra de Deus.\n',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'A GRAÇA DO SANTO JARDIM',
    '7',
    [
      'A Graça enche o meu ser\nBênção Divina sem par\nA vida eterna Deus me dá\nPerfeita é minha alegria.',
      'Entoa minha alma\nUm hino de glória\nAo meu Pai Celestial\nE com gratidão ofertar-Lhe-ei\nO mais sublime amor.',
      'Tanta alegria nasce em mim\nTal como as ondas do mar\nCanto louvores ao Senhor\nQue nos traz a perfeição.',
      'Entoa minha alma\nUm hino de glória\nAo meu Pai Celestial\nE com gratidão ofertar-Lhe-ei\nO mais sublime amor.',
      'Tão incomensurável dom\nPossuir a vida eterna\nDou graças com todo o meu ser\nPor tal bênção imortal.',
      'Entoa minha alma\nUm hino de glória\nAo meu Pai Celestial\nE com gratidão ofertar-Lhe-ei\nO mais sublime amor.',
      'Fui escolhido p’ra fazer\nVossa Vontade Divina\nPai, juro no meu coração\nA minha vida Vos dou.',
      'Entoa minha alma\nUm hino de glória\nAo meu Pai Celestial\nE com gratidão ofertar-Lhe-ei\nO mais sublime amor.',
    ],
    SongsCategory.holy,
    isSecondChorus: true,
  ),
  SongsModel(
    'A MINHA OFERTA',
    '8',
    [
      'Agora na verdade já compreendi\nPai, Teu coração está sofrendo\nPois o Teu altar espera\nA oferta nunca feita.\nOs longos anos passam\nE a oferta sem chegar\nO Pai chora em solidão\nSem ninguém O confortar.',
      'Agora na verdade já compreendi\nPai, eu já conheço a Tua graça\nPois tiraste-me da escuridão\nE deste-me a vida.\nAgora já sou Teu,\nMas Tu choras ainda\nMeu Pai tens de me dizer:\n"Vai e morre no meu lugar."',
      'Eu juro que irei Determinado estou\nPai, eu venho agora para Ti\nPois não tenho outra vontade\nSenão seguir a Tua.\nNo Teu altar me ponho\nE sem hesitação\nA minha vida há-de ser\nUma pura oblação.',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'BENÇÃO DE GLÓRIA',
    '9',
    [
      'Hoje a luz da glória se ergue\n Como o Sol no seu fulgor\n Já em plena liberdade renascei,\n Vós todos renascei,\n Despertai a terra inteira\n Para a nova vida que surge\n Brilhe a luz da vossa nova vida\n Para sempre.',
      'Para sermos Seus testemunhos,\n Deus nos chama a todos nós\n O Senhor na Sua bondade nos abraça\n Com o Seu amor,\n Procurando e chamando todos\n Para a liberdade.\n Que resposta Lhe vou dar,\n Ele que chama por mim.',
      'Acordei da morte p\'ra vida,\n sou feliz vivendo em graça\n Quando aquele que me salvou\n me segura nos Seus ternos braços\n Rejubilo por sentir o amor\n Que Ele tem por mim\n Oh, que bênção de glória\n Para sempre vou cantar',
      'Ele me ergue agora e me abraça\n Nesta bênção que me deu\n Que alegria é recebê-Lo\n Num amor tão puro e tão divino\n Por maior que seja o meu ardor\n Nunca Lhe retribuirei\n Sempre hei-de me sentir\n Como tão indigno sou',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'NASCENTE DA VIDA',
    '10',
    [
      'Nós vamos exultantes\n Para a Terra Prometida\n Deixando cá nosso pesado fardo.\n E finalmente livres\n Das cadeias do pecado\n Nós vamos para a nascente da vida.',
      'Vamos à nascente\n Onde brota a água viva\n Na glória eternamente viveremos.\n Vamos para a terra\n Das águas cristalinas\n Felizes para sempre viveremos.',
      'Oh!, guia-nos Senhor\n Com o fogo da verdade\n E ensina-nos a seguir Teus caminhos.\n Está próximo o momento\n De passar o Rio Jordão\n Nós vamos para a nascente da vida.',
      'Vamos à nascente\n Onde brota a água viva\n Na glória eternamente viveremos.\n Vamos para a terra\n Das águas cristalinas\n Felizes para sempre viveremos.',
      'Os nossos corações anseiam\n P\'lo maná do céu\n Teu alimento será nossa força.\n E na adversidade\n Nunca desesperaremos\n Nós vamos para a nascente da vida.',
      'Vamos à nascente\n Onde brota a água viva\n Na glória eternamente viveremos.\n Vamos para a terra\n Das águas cristalinas\n Felizes para sempre viveremos.',
    ],
    SongsCategory.holy,
    isSecondChorus: true,
  ),
  SongsModel(
    'CÂNTICO DO JARDIM',
    '11',
    [
      'O Senhor vem ao Seu Jardim\n As flores exalam seu perfume;\n E os lírios desabrocham,\n E os lírios desabrocham.\n Chuva de graça divinal\n Traz do Pai a vida sem igual;\n E faz voltar à vida,\n E faz voltar à vida.',
      'Oh! que este solo tão estéril\n Se faça rico em nascentes;\n Se torne um solo fértil,\n Se torne um solo fértil.\n E o deserto florirá\n Quando o Senhor vence a maldade;\n E une o seu povo,\n E une o seu povo.',
      'Todos que amais o Senhor\n Vinde e provai da Sua Palavra;\n Seguindo sempre o Pai,\n Seguindo sempre o Pai.\n Nossas tribulações aqui\n Serão a nossa riqueza lá;\n No nosso eterno lar,\n No nosso eterno lar.',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'DEUS É AMOR',
    '12',
    [
      'Ó Luz Divina, resplandecente,\n Tu alumias meu caminho\n Ó Luz Divina, alívio na dor,\n Tu me mostras Deus é amor.',
      'A minha vida e o meu amor\n Vou consagrar ao Deus de amor.',
      'Mesmo que as nuvens\n Escondam a Sua face,\n Escondam o sorriso do meu Deus,\n Mesmo assim, Ele está lá,\n Em esplendor, Deus é amor.',
      'A minha vida e o meu amor\n Vou consagrar ao Deus de amor.',
      'Na tempestade, p\'lo mar batido,\n Farol potente Tu me guias,\n Na tempestade, abrigo certo,\n Crê n\'Ele, pois Deus é amor.',
      'A minha vida e o meu amor\n Vou consagrar ao Deus de amor.',
      'Tudo se esvai e desvanece\n Somente a luz permanece,\n Tudo se esvai, mas há um só,\n Real e fiel, Deus é amor.',
      'A minha vida e o meu amor\n Vou consagrar ao Deus de amor.',
    ],
    SongsCategory.holy,
    isSecondChorus: true,
  ),
  SongsModel(
    'CANÇÃO DA JUVENTUDE',
    '13',
    [
      'Ergamo-nos em júbilo!\n A Vontade de Deus se fez!\n Nova aurora, novo dia\n Já o Senhor chegou!\n Satanás esmagaremos\n E Deus mostrará Seu poder\n Nos Seus filhos,\n Juventude de harmonia e amor!',
      'A escuridão que nos cobriu\n Com Ele se dissipou\n A manhã já anuncia\n Um dia de fulgor!\n Todo o cosmos viverá\n Na luz brilhante da Verdade\n Sempre em frente\n Juventude de harmonia e amor!',
      'Nós somos filhos verdadeiros\n Do Pai Celestial\n Formaremos cá na terra\n O mundo ideal!\n Novo mundo de alegria\n De luz, amor e muita paz\n Sempre em frente\n Juventude de harmonia e amor!',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'CANÇÃO DA PRIMAVERA DO ÉDEN',
    '14',
    [
      'Vinde irmãos para o Jardim do Éden\n A primavera chegou! \n Alegremente cantemos unidos \n No Éden já restaurado \n Neste Jardim todos festejaremos \n Com canções de alegria.',
      'Vinde irmãos para o Jardim do Éden\n Cantando novas canções\n Vibremos todos num só coração \n No Éden rejubilemos\n Neste Jardim de harmonia exultemos \n Com canções de alegria.',
      'Vinde irmãos para o Jardim do Éden \n Reino da felicidade\n Em comunhão nosso amor partilhando\n No nosso Éden da paz\n Vinde p\'ra este Jardim, meus irmãos \n Com canções de alegria',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'CANÇÃO DA VITÓRIA',
    '15',
    [
      'Canta Hosanas Aleluia\n Glória, glória eternamente\n O Senhor já regressou\n Canta Hosanas Aleluia.',
      'Todo o céu exulta e canta\n E os anjos rejubilam\n E a inteira criação\n Compartilha da alegria.',
      'Já a Nova Jerusalém\n Vem descendo sobre a terra\n Por fim o dia chegou\n Em que o Senhor voltou.',
      'Vivo fogo da fé\n Brilhando por toda a parte\n Luz de nova esperança\n Que inflama os corações.',
      'Ó Egipto terra de dor\n Que esperas o Senhor\n Breve chegará o dia\n Em que todos exultarão.',
      'Para a frente caminhai\n Sem receio avançai\n Pois seguis para a vitória\n Soldados celestiais.',
      'Glória, glória ao Senhor\n Da verdade e do amor\n Ao Senhor cantai hinos\n De eterna gratidão.',
      'Canta Hosanas Aleluia\n Glória, glória eternamente\n O Senhor já regressou\n Canta Hosanas Aleluia.',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
      'CANÇÃO DOS VITORIOSOS',
      '16',
      [
        'Cantai alto hosana ao Senhor,\n Oferecei-Lhe tudo com amor,\n Servi o Senhor, n\'Ele exultai\n Que traz nova vida ao mundo.\n Decididos vamos hoje encontrar,\n Toda a glória que nos dá o Senhor.',
        'Ao Jardim iremos para cantar\n A canção de liberdade e amor.\n Ao Jardim iremos para cantar\n A canção de liberdade e amor.',
        'Escuras nuvens toldam o caminho,\n O pecado a terra povoa,\n Vamos pois rasgar esta escuridão\n E olhar a bela luz brilhante,\n Decididos vamos hoje encontrar\n Nosso mundo de alegria e paz.',
        'Ao Jardim iremos para cantar\n A canção de liberdade e amor.\n Ao Jardim iremos para cantar\n A canção de liberdade e amor.',
        'Alegrai-vos hoje meus irmãos,\n Que cantais já a nova canção,\n Elevai louvores ao alto\n Sois escolhidos do Senhor,\n Decididos vamos hoje encontrar\n Nosso mundo de alegria e paz.',
        'Ao Jardim iremos para cantar\n A canção de liberdade e amor.\n Ao Jardim iremos para cantar\n A canção de liberdade e amor.',
        'Defendemos o padrão de Deus,\n P\'ra restaurar o Seu ideal,\n Dai o vosso amor livremente ao Pai\n E a beleza volverá p\'ra vós,\n Decididos vamos hoje encontrar\n Nosso mundo de alegria e paz.\n',
        'Ao Jardim iremos para cantar\n A canção de liberdade e amor.\n Ao Jardim iremos para cantar\n A canção de liberdade e amor.',
      ],
      SongsCategory.holy,
      isSecondChorus: true),
  SongsModel(
    'NOVA CANÇÃO DA INSPIRAÇÃO',
    '17',
    [
      'Nasci aqui sobre esta terra preparada por Deus,\n Uma terra de liberdade, tenho a missão de construir,\n Revelar a verdade de Deus, Seu propósito e Sua vontade,\n Imolai-vos e vivei, pelo Seu desejo, pelo Seu desejo.',
      'Canta o céu, belas canções, de divina inspiração,\n A todos dai a mensagem, Novo Éden se abriu,\n Imolai-vos e construí o mundo do Senhor,\n Procurai a Nova Terra, pelo Seu desejo, pelo Seu desejo.',
      'Nós procuramos a base eterna, a Família de Deus,\n Há já muito esperada pelo Pai Celestial,\n Proclamai esta verdade de esperança e de bondade,\n Pioneiro da Nova Era, pelo Seu desejo, pelo Seu desejo.',
      'Já neste dia de nova vida, defendei a justiça,\n E a nova vida eterna, erguei o padrão do bem,\n Glória ao Pai de todo o bem, nosso grande ideal,\n Construí um Novo Mundo, de paz e amor, Vamos construir.',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'O SENHOR CHEGOU',
    '18',
    [
      'O Senhor chegou, o Senhor chegou,\n Ele veio do país de Deus,\n Como alvorada brilhante,\n É nosso Mestre e Senhor,\n Cheio da Luz do Pai.\n Sua palavra conduz\n Todos os homens a Deus,\n Terra bendita recebe o Senhor,\n Cantemos com alegria.\n Aleluia, Aleluia, Aleluia, Adju.',
      'O Senhor chegou, o Senhor chegou,\n Ele veio à terra dos puros,\n Abençoada por Deus,\n É nosso Rei e Senhor,\n Caminho para o Pai.\n Destruindo o mal\n Construindo o Céu,\n Terra bendita recebe o Senhor,\n Cantemos com a alegria.\n Aleluia, Aleluia, Aleluia, Adju.',
      'O Senhor chegou, o Senhor chegou,\n Veio à terra dos montes e vales,\n E de tesouros sem par,\n É nosso Deus e Senhor,\n Traz o amor do Pai.\n Eleva todos ao Céu,\n Junto à glória de Deus,\n Vinde irmãos receber o Senhor,\n Cantemos com a alegria.\n Aleluia, Aleluia, Aleluia, Adju.',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
      'O SENHOR ME CHAMOU',
      '19',
      [
        'A voz do meu Senhor chamou,\n Aonde quer que eu vá irei,\n Na dor e na alegria vou,\n Junto a ele andarei',
        'Quem poderá me separar\n Nem mesmo a morte impede. (Bis)',
        'Aos vales desolados vou\n Levarei a nova vida\n Até nas ruas de Sodoma\n A palavra espalharei',
        'Minha vida à Tua ligarei\n Meu coração é oferta. (Bis)',
        'A Ti pertence todo o poder\n Toda honra, fama e glória\n A mim desprezo e rejeição\n Carregar a cruz eu devo',
        'Renome não procuro eu\n Desejo só seguir-Te. (Bis)',
      ],
      SongsCategory.holy,
      isSecondChorus: true),
  SongsModel(
    'TONGIL',
    '20',
    [
      'Urie so wonun tonguil,\n Gumedo so wonun tonguil,\n I magsum bachoso tonguil,\n Tonguiri ora!\n I kyo re sallinun tonguil\n Inara channunde tonguil\n Tonguiri oso ora,\n Tonguiri ora!',
      'A nossa esperança é a Unificação,\n Sonhamos com a Unificação,\n Damos a vida pela Unificação,\n Vem Unificação!\n Pr\'a salvar a humanidade,\n Pr\'a salvar todo o mundo,\n Vem depressa Unificação,\n Vem Unificação!',
      'Our cherished hopes are for unity,\n Even our dreams are for unity,\n We\'ll give our lives for unity,\n Come along unity!\n Unity saving the people,\n Unity saving all nations,\n Come here quickly unity,\n Come along unity!',
    ],
    SongsCategory.holy,
  ),
  SongsModel(
    'A FORÇA DO AMOR',
    '22',
    [
      'Se procuras um ideal\n E não encontras neste mundo de mal,\n A pureza, a certeza, o amor!\n Tem coragem meu irmão,\n Este mundo é uma miragem uma ilusão!\n Não te deixes arrastar,\n Reforça a tua fé à vontade,\n Que o amor hás de encontrar!',
      'É a força do amor\n Que faz o mundo melhor,\n De alegria, de vontade,\n De harmonia e verdade!\n Está dentro de ti\n Essa força de vencer,\n Semeia, porque alguém irá colher.\n O amor que fazes nascer!\n O amor que fazes nascer!',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
    'À LUZ DO SOL',
    '23',
    [
      'Vamos caminhar à luz do sol\n Vamos caminhar à luz do luar\n Sob as estrelas do céu, vamos cantar\n Sun Myung Moon por Deus enviado\n Mostra-nos o caminho por Deus traçado\n Para um novo mundo sobre a terra começar.',
      'Vinde todos que aspirais a um novo mundo de bondade,\n Vinde todos vós que buscais um mundo novo de verdade,\n Vinde todos que ansiais por um mundo de pureza,\n Vinde todos que procurais um mundo novo de beleza.',
      'Vamos caminhar à luz do sol\n Vamos caminhar à luz do luar\n Sob as estrelas do céu, vamos cantar\n Sun Myung Moon por Deus enviado\n Mostra-nos o caminho por Deus traçado\n Para um novo mundo sobre a terra começar.',
      'Pela paz vós que lutais, deixai de fazer mais mal,\n Na guerra não a encontrais, está em Deus esse ideal.\n Neste mundo sem destino, sem ordem nem harmonia,\n Deus nos mostra o caminho, e hoje é esse grande dia.',
      'Vamos caminhar à luz do sol\n Vamos caminhar à luz do luar\n Sob as estrelas do céu, vamos cantar\n Sun Myung Moon por Deus enviado\n Mostra-nos o caminho por Deus traçado\n Para um novo mundo sobre a terra começar.',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
      'A MONTANHA',
      '24',
      [
        'Eu vou seguir, uma luz lá no alto\n Eu vou ouvir, uma voz que me chama\n Eu vou subir, a montanha e ficar\n Bem mais perto de Deus e rezar.',
        'Eu vou gritar, para o mundo me ouvir\n E acompanhar, toda a minha escalada\n E ajudar, a mostrar como é\n O meu grito de amor e de fé.',
        'Eu vou pedir que as estrelas não parem\n De brilhar, e as crianças não deixem\n De sorrir, e que os homens jamais\n Se esqueçam de agradecer.',
        'Por isso eu digo, obrigado Senhor\n Por mais um dia, obrigado Senhor\n Eu posso ver, que seria de mim\n Sem a fé que eu tenho em Você.',
        'Por mais que eu sofra, obrigado Senhor\n Mesmo que eu chore, obrigado Senhor\n Por eu saber, e tudo isto me mostra\n O caminho que leva a Você.',
        'Mais uma vez, obrigado Senhor\n Por outro dia, obrigado Senhor\n Que o sol nasceu, obrigado Senhor\n Agradeço, obrigado Senhor.',
        'Por isso eu digo, obrigado Senhor\n Pelas estrelas, obrigado Senhor\n Pelo sorriso, obrigado Senhor\n Agradeço, obrigado Senhor.',
        'Mais uma vez, obrigado Senhor\n Por um novo dia, obrigado Senhor\n Pela esperança, obrigado Senhor\n Agradeço, obrigado Senhor.',
      ],
      SongsCategory.convivial),
  SongsModel(
      'A PLAINA',
      '25',
      [
        'A plaina corre ligeira\n Chária, chária, chária-ó\n Tornando lisa a madeira\n Chária, chária, chária-ó\n No viçoso bosque em flor\n Sente-se o mesmo rumor\n Chária, chária, chária,\n Chária, chária, chária-ó.',
        'Ao longe se ouve cantar\n Crissa, crissa, crissa-ó\n O lenhador a serrar\n Crissa, crissa, crissa-ó\n Na bigorna do ferreiro\n Bate o martelo certeiro\n Crissa, crissa, crissa,\n Crissa, crissa, crissa-ó.',
      ],
      SongsCategory.convivial),
  SongsModel(
      'A VIDA É TÃO BELA',
      '26',
      [
        'Vejo um rosto a sorrir\n Que está bem perto de mim,\n Ele diz que a vida é servir\n E a alegria é assim.',
        'A vida é tão bela\n Vamos começar\n A saber tudo dela\n E aprender a amar.',
        'Em cada rosto um sorriso,\n Em cada homem um irmão,\n Um mundo de paraíso,\n Já não é ilusão.',
        'A vida é tão bela\n Vamos começar\n A saber tudo dela\n E aprender a amar.',
        'Neste dia de esperança,\n Outro mundo vai surgir,\n E de novo as crianças,\n Vão voltar a sorrir.',
        'A vida é tão bela\n Vamos começar\n A saber tudo dela\n E aprender a amar.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
      'A VOZ DO PAI',
      '27',
      [
        'Eu vou ao jardim do meu pai\n Vou ouvir sua voz tao graciosa\n Que enche o coração de consolação\n Que só o filho goza.',
        'Qual maior prazer que ouvir dizer\n Vem meu filho vem escutar\n Sobre o amor de deus e os cuidados seus\n Para o mundo restaurar.',
        'Falou me com tanta emoção\n Da verdade que eu procurava\n Quando aquilo ouvi pude então fugir\n Do mal que me enganava.',
        'Qual maior prazer que ouvir dizer\n Vem meu filho vem escutar\n Sobre o amor de deus e os cuidados seus\n Para o mundo restaurar.',
        'O pai não me deixa sofrer\n Sua voz me ensina o caminho\n De vencer o mal com firmeza tal\n Que nunca estou sozinho.',
        'Qual maior prazer que ouvir dizer\n Vem meu filho vem escutar\n Sobre o amor de deus e os cuidados seus\n Para o mundo restaurar.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
      'ALECRIM',
      '28',
      [
        'Alecrim, alecrim doirado\n Que nasceu no monte\n Sem ser semeado,\n Alecrim, alecrim doirado\n Que nasceu no monte\n Sem ser semeado.',
        'Ai, meu amor quem te disse a ti\n Que a flor do monte era o alecrim. (Bis)',
        'Alecrim, alecrim aos molhos\n Por causa de ti\n Choram os meus olhos,\n Alecrim, alecrim aos molhos\n Por causa de ti\n Choram os meus olhos.',
        'Ai, meu amor quem te disse a ti Que a flor do monte era o alecrim. (Bis)',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'ALVO SUPREMO',
    '29',
    [
      'O mundo vil já desprezei\n E seu caminho abominei,\n Mas te suplico, ó Salvador\n A ti me eleva, Redentor.',
      'Mais perto sim, mais perto sim\n Oh! Junto a ti eleve a mim\n Ao céu em que meu Salvador\n Contigo esteja sem temor.',
      'No mundo não encontro paz,\n Pois ele não me satisfaz\n Aqui só tenho que sofrer\n Contigo quero, pois viver.',
      'Mais perto sim, mais perto sim\n Oh! Junto a ti eleve a mim\n Ao céu em que meu Salvador\n Contigo esteja sem temor.',
      'Desejo sim, aqui viver\n Por tua causa me bater,\n Já pela fé eu avistei\n O lar em que descansarei.',
      'Mais perto sim, mais perto sim\n Oh! Junto a ti eleve a mim\n Ao céu em que meu Salvador\n Contigo esteja sem temor.',
    ],
    SongsCategory.convivial,
    isSecondChorus: true,
  ),
  SongsModel(
      'AMAR COMO JESUS AMOU',
      '30',
      [
        'Um dia uma criança me parou,\n Olhou-me nos meus olhos a sorrir,\n Caneta e papel na sua mão,\n Tarefa escolar para cumprir,\n E perguntou-me no meio dum sorriso\n O que é preciso para ser feliz.',
        'Amar como Jesus amou, sonhar como Jesus \n sonhou, pensar como Jesus pensou, viver como Jesus viveu;\n Sentir como Jesus sentia, \n Sorrir como Jesus sorria, \n E ao chegar ao fim do dia \n Eu sei que dormiria muito mais feliz. (Bis)',
        'Ouvindo o que eu falei ela me olhou\n E disse que era lindo o que eu falei,\n Pediu que eu repetisse por favor,\n Que não falasse tudo de uma vez\n E perguntou de novo num sorriso\n O que é preciso para ser feliz.',
        'Amar como Jesus amou, sonhar como Jesus \n sonhou, pensar como Jesus pensou, viver como Jesus viveu;\n Sentir como Jesus sentia, \n Sorrir como Jesus sorria, \n E ao chegar ao fim do dia \n Eu sei que dormiria muito mais feliz. (Bis)',
        'Depois que eu terminei de repetir,\n Seus olhos não saíam do papel,\n Toquei no seu rostinho e a sorrir,\n Pedi que ao transmitir fosse fiel\n E ela deu-me um beijo demorado\n E ao meu lado foi dizendo assim.',
        'Amar como Jesus amou, sonhar como Jesus \n sonhou, pensar como Jesus pensou, viver como Jesus viveu;\n Sentir como Jesus sentia, \n Sorrir como Jesus sorria, \n E ao chegar ao fim do dia \n Eu sei que dormiria muito mais feliz. (Bis)',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'EU GOSTO DE VER',
    '31',
    [
      'Eu gosto de ver o sol a nascer em cada manhã,\n Eu gosto de olhar e contemplar\n A natureza que é minha irmã,\n Eu gosto de aceitar a surpresa em cada dia,\n E de contar com firmeza uma canção de alegria,\n Eu gosto de sentir a paz em meu coração,\n E de encontrar em cada dia um novo irmão,\n Que comigo, queira cantar esta canção.',
      'Eu gosto de olhar à noite o luar p\'la minha janela,\n Eu gosto de viver e amar a vida que é tão bela,\n Eu gosto de ver as crianças correrem p\'ra escola,\n E de saber que os velhos não pedem esmola,\n Eu gosto de sentir a paz em meu coração,\n E de encontrar em cada dia um novo irmão.\n Que comigo, queira cantar esta canção\n De amor!',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
    'EU NUNCA MAIS O DEIXAREI',
    '32',
    [
      'Eu nunca mais O deixarei,\n Pois encontrei no Seu olhar,\n Um rio de amor, um coração de ouro\n E mãos de paz para segurar.',
      'E o que farei com este dom?\n Devo abraçá-lo só para mim?\n Não posso não, pois o perderia,\n Deve ser dado para durar.',
      'E um novo mundo vamos construir,\n Um lugar p’ra reis e p’ra rainhas,\n Vamos elevá-los p’ra reger a terra,\n E por dominio nas Suas mãos.',
      'Nós nunca mais O deixaremos,\n Pois encontrámos no Seu olhar, \n Um rio de amor, um coração de ouro\n E mãos de paz para segurar.',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
      'EU QUERO APENAS',
      '33',
      [
        'Eu quero apenas olhar os campos\n Eu quero apenas cantar meu canto\n Eu só não quero é cantar sozinho\n Eu quero um coro de passarinhos\n',
        'Quero levar o meu canto amigo\n A qualquer amigo que precisar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar',
        'Eu quero apenas que um vento forte\n Leve meu barco no rumo norte\n E no caminho o que eu pescar\n Quero dividir quando lá chegar',
        'Quero levar o meu canto amigo\n A qualquer amigo que precisar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar',
        'Eu quero crer na paz do futuro\n Eu quero ter um quintal sem muro\n Quero meu filho pisando firme\n Cantando alto, sorrindo livre',
        'Quero levar o meu canto amigo\n A qualquer amigo que precisar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar',
        'Eu quero amor decidindo a vida\n Sentir a força da mão amiga\n E ao meu irmão com sorriso aberto\n Se ele chorar quero estar por perto',
        'Quero levar o meu canto amigo\n A qualquer amigo que precisar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar',
        'Venha comigo olhar os campos\n Canta comigo também meu canto\n Eu só não quero é cantar sozinho\n Eu quero um coro de passarinhos',
        'Quero levar o meu canto amigo\n A qualquer amigo que precisar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar\n Eu quero ter um milhão de amigos\n E bem mais forte poder cantar',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'JUNTO A TI',
    '34',
    [
      'Tu Te abeiraste da praia\n Não buscaste nem sábios nem ricos\n Somente queres que eu Te siga.',
      'Senhor, Tu me olhaste nos olhos\n A sorrir, pronunciaste meu nome\n Lá na praia eu larguei o meu barco\n Junto a Ti buscarei outro mar.',
      'Tu sabes bem que em meu barco\n Eu não levo nem ouro nem espada\n Somente redes e o meu trabalho.',
      'Senhor, Tu me olhaste nos olhos\n A sorrir, pronunciaste meu nome\n Lá na praia eu larguei o meu barco\n Junto a Ti buscarei outro mar.',
      'Tu minhas mãos solicitas\n Meu cansaço que a outros descanse\n Amor que almeja seguir amando.',
      'Senhor, Tu me olhaste nos olhos\n A sorrir, pronunciaste meu nome\n Lá na praia eu larguei o meu barco\n Junto a Ti buscarei outro mar.',
      'Tu pescador de outros lagos\n Ânsia eterna de almas que esperam\n Bondoso amigo que assim me chama.',
      'Senhor, Tu me olhaste nos olhos\n A sorrir, pronunciaste meu nome\n Lá na praia eu larguei o meu barco\n Junto a Ti buscarei outro mar.',
    ],
    SongsCategory.convivial,
    isSecondChorus: true,
  ),
  SongsModel(
    'MALMEQUER – BEMMEQUER ',
    '35',
    [
      'Ó malmequer mentiroso, quem te ensinou a mentir,\n Tu dizes que me queres bem, quem te via a andar comigo.',
      'Desfolhei o malmequer Malmequer,\n Num lindo jardim de Santarém,\n Malmequer, bem me quer\n Muito longe está quem me quer bem.',
      'O malmequer pequeninho, disse um dia à linda rosa,\n Por te chamarem rainha, não sejas tão orgulhosa.',
      'Desfolhei o malmequer Malmequer,\n Num lindo jardim de Santarém,\n Malmequer, bem me quer\n Muito longe está quem me quer bem.',
      'Malmequer não é constante, malmequer muito varia,\n Vinte folhas dizem morte, treze dizem alegria.',
      'Desfolhei o malmequer Malmequer,\n Num lindo jardim de Santarém,\n Malmequer, bem me quer\n Muito longe está quem me quer bem.',
      'Coitado do malmequer, sem fazer mal a ninguém,\n São todos a desfolhá-lo para ver quem lhe quer bem.',
      'Desfolhei o malmequer Malmequer,\n Num lindo jardim de Santarém,\n Malmequer, bem me quer\n Muito longe está quem me quer bem.',
    ],
    SongsCategory.convivial,
    isSecondChorus: true,
  ),
  SongsModel(
    'NO ESPÍRITO UNIDOS',
    '36',
    [
      'No espírito unidos somos um no Senhor (Bis)\n E imploramos que um dia nos unamos no amor\n Pelo amor conhecido é o cristão, pelo amor,\n Pelo amor conhecido é o cristão.',
      'De mãos dadas iremos somos todos irmãos (Bis)\n Pregaremos a nova que Deus guia a nação\n Pelo amor conhecido é o cristão, pelo amor,\n Pelo amor conhecido é o cristão.',
      'Lado a lado haveremos todos de trabalhar (Bis)\n Uns aos outros honrando vamo-nos respeitar\n Pelo amor conhecido é o cristão, pelo amor,\n Pelo amor conhecido é o cristão.',
      'No espírito unidos somos um no Senhor (Bis)\n E imploramos que um dia nos unamos no amor\n Pelo amor conhecido é o cristão, pelo amor,\n Pelo amor conhecido é o cristão.',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
      'O AMOR ME TRANSFORMOU',
      '37',
      [
        'Eu perdido pecador, sem nada conhecer,\n Já me achava sem vigor, prestes a perecer,\n Meu estado o Mestre viu, dando-me sua mão,\n E salvar-me conseguiu da perdição',
        'Ele me amou, e me livrou\n O seu imenso amor me transformou,\n Foi seu poder, o seu querer,\n Sim, com o seu amor o Pai, me transformou.',
        'Minha vida, todo o ser,\n Quero-lhe consagrar,\n A seu lado vou viver, o seu valor cantar\n A mensagem transmitir aos que perdidos estão,\n Venham todos já fruir da salvação.',
        'Ele me amou, e me livrou\n O seu imenso amor me transformou,\n Foi seu poder, o seu querer,\n Sim, com o seu amor o Pai, me transformou.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
      'ORAÇÃO DA NOITE',
      '38',
      [
        'Mais outro dia findou\n Eu venho te ver, para conversar\n Mais outra noite chegou\n Eu venho agradecer, antes de repousar.',
        'Andei o dia inteiro procurando meu irmão\n Eu quis ser instrumento do teu amor, Do teu perdão.',
        'Muito obrigado, Senhor\n Pelo amor que ensinei, Pelo amor que eu recebi\n Muito obrigado Senhor\n Pela dor que suavizei, Por sorrisos que sorri.',
        'Andei o dia inteiro procurando meu irmão\n Eu quis ser instrumento do teu amor, Do teu perdão.',
        'Sou peregrino do amor\n E venho agradecer o dia que vivi\n Houve tristezas, Senhor\n Mas eu não quis sofrer, Pois caminhei em ti.',
        'Andei o dia inteiro procurando meu irmão\n Eu quis ser instrumento do teu amor, Do teu perdão.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'RAMA QUE LINDA RAMA',
    '39',
    [
      'Ó rama ó que linda rama\n Ó rama da oliveira\n O meu par é o mais lindo\n Que anda a aqui na roda inteira',
      'Que anda aqui na roda inteira\n Aqui e em qualquer lugar\n Ó rama ó que linda rama\n Ó rama do olival',
      'Ó rama ó que linda rama\n Ó rama da oliveira\n O meu par é o mais lindo\n Que anda a aqui na roda inteira',
      'Eu gosto muito de ouvir\n Cantar a quem aprendeu\n Se houvera quem me ensinara\n Quem aprendia era eu',
      'Ó rama ó que linda rama\n Ó rama da oliveira\n O meu par é o mais lindo\n Que anda a aqui na roda inteira',
      'Não me inveja de quem tem\n Parelhas éguas e montes\n Só me inveja de quem bebe\n A água em todas as fontes\n',
      'Ó rama ó que linda rama\n Ó rama da oliveira\n O meu par é o mais lindo\n Que anda a aqui na roda inteira',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
    'PROCURA A PAZ',
    '40',
    [
      'Procura a paz e o amor,\n Assim terás um mundo melhor.\n Procura a paz e a alegria,\n Assim verás nascer um novo dia.',
      'Basta apenas um sorriso\n Para mover um coração\n E nada mais é preciso\n P\'ra alegrar o teu irmão.',
      'Procura a paz e o amor,\n Assim terás um mundo melhor.\n Procura a paz e a alegria,\n Assim verás nascer um novo dia.',
      'Neste mundo dividido\n Já não resta esperança\n Eu e tu meu amigo\n Façamos nova mudança.',
      'Procura a paz e o amor,\n Assim terás um mundo melhor.\n Procura a paz e a alegria,\n Assim verás nascer um novo dia.',
      'Começa dentro de ti\n Este novo amanhecer\n E se alguém te sorri\n Não queiras o entardecer.',
      'Procura a paz e o amor,\n Assim terás um mundo melhor.\n Procura a paz e a alegria,\n Assim verás nascer um novo dia.',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
      'QUÃO GRANDE ÉS TU',
      '41',
      [
        'Ó grande Deus, ao ver o universo\n Que Tu criaste pelo Teu querer,\n Que sapiente, guias cada astro\n E em tudo operas pelo Teu poder.',
        'Canta minha alma, canta ao Senhor\n Quão grande és Tu, quão grande és Tu.',
        'E quando enfim, o véu que nos separa,\n Ele for rasgado, então eu Te verei\n No céu jamais hei-de sentir-me estranho,\n Eternamente, como Tu serei.',
        'Canta minha alma, canta ao Senhor\n Quão grande és Tu, quão grande és Tu.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'SEI QUE ÉS CAPAZ',
    '42',
    [
      'Sei que és capaz de fazer muito melhor,\n Sei que encontrarás a alegria e o amor.',
      'Que te fará renascer neste mundo de escuridão,\n Que te fará viver não mais em solidão.',
      'Há muito à tua frente para conheceres melhor,\n Se queres ser diferente caminha no amor.',
      'O amor rasga barreiras, o amor gera alegria,\n O amor não tem fronteiras, o amor é dia.',
      'La la la la la .........\n Sei que és capaz .........',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
    'TODO O MUNDO TE PERTENCE',
    '43',
    [
      'Senhor todo o mundo Te pertence\n E Tu sempre fazes tudo novo\n Tu perdoas o mal, e nova vida dás\n E assim fazes o mundo girar.',
      'Neste mundo triste e desunido\n Tu dás-nos amor que nunca finda\n Amando os inimigos e neste amor Contigo,\n Assim fazes o mundo unido.',
      'Senhor todo o mundo Te pertence\n E Tu sempre fazes tudo novo\n Faz descer sobre nós, Tua luz e amor\n E assim tornas o mundo sem dor.',
    ],
    SongsCategory.convivial,
  ),
  SongsModel(
    'UMA NOVA CANÇÃO',
    '44',
    [
      'Eu quero cantar uma nova canção\n Para alegrar o teu coração,\n Que vive frustrado na dor e lamento,\n Eu quero cantar uma nova canção\n Que já é tempo.',
      'Tempo de a cantar, tempo de a viver,\n É tempo de amar e de renascer, \n Olhar o mundo, encontrar um irmão,\n É tempo de cantar uma nova canção.',
      'Eu quero cantar uma nova canção\n Para alegrar o teu coração,\n Que vive frustrado na dor e lamento,\n Eu quero cantar uma nova canção\n Que já é tempo.',
      'Tempo de a cantar, tempo de a viver\n É tempo de amar e de renascer, \n Semear a paz, colher uma flor,\n É tempo de cantar uma canção de amor.\n',
      'Eu quero cantar uma nova canção\n Para alegrar o teu coração,\n Que vive frustrado na dor e lamento,\n Eu quero cantar uma nova canção\n Que já é tempo.',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
    'VAMOS A CAMINHO DO TEU REINO',
    '45',
    [
      'Vamos a caminho do teu reino\n Vamos p’ra terra prometida,\n Em direção à liberdade\n Vamos de mãos dadas contigo.',
      'Dá-me a tua mão e seguiremos\n P’ra o novo mundo de alegria\n Vamos esquecer o mundo antigo\n Há novo mundo a descobrir.',
      'Vamos a caminho do teu reino\n Vamos p’ra terra prometida,\n Em direção à liberdade\n Vamos de mãos dadas contigo.',
      'Desde o começo até ao fim\n Desde o fim até ao presente,\n Deus derramou o seu amor\n Ele nos chama com ternura.',
      'Vamos a caminho do teu reino\n Vamos p’ra terra prometida,\n Em direção à liberdade\n Vamos de mãos dadas contigo.',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
    'VAMOS SEGUIR EM FRENTE',
    '46',
    [
      'Vamos seguir em frente,\n Sob a luz do sol do oriente\n Do manto da noite livres, \n Filhos da luz somos,\n Caminhando no Teu caminho.',
      'Querido Pai, Tua voz seremos\n E mensageiros da Tua verdade,\n Por toda a parte teus caminheiros iremos,\n Manifestar Tua vontade.',
      'Vamos seguir em frente,\n Sob a luz do sol do oriente\n Do manto da noite livres, \n Filhos da luz somos,\n Caminhando no Teu caminho.',
      'Querido Pai, Tuas mãos seremos\n Para o Teu reino construir\n Aplanaremos montanhas, encheremos vales,\n Dar-Te-emos todo este mundo.',
      'Vamos seguir em frente,\n Sob a luz do sol do oriente\n Do manto da noite livres, \n Filhos da luz somos,\n Caminhando no Teu caminho.',
    ],
    SongsCategory.convivial,
    isFirstChorus: true,
  ),
  SongsModel(
    'SOLDADOS UNIDOS (BRASIL)',
    '47',
    [
      'A força da união faz o mundo renascer.\n Sempre em unidade no amor todos devem viver.\n Nós devemos compartilhar aqui, em nosso lar,\n eternamente o fundamento para o bem e a felicidade.',
      'Hey, avançar soldados unidos, \n O inimigo derrotar.\n Lado a lado a lutar e em frente marchar, marchar',
      'Verdadeiros homens de fé magnificam sua luz\n Gloriosa luz de verdade, ilumina a terra\n Do mundo original a vida resplandecerá\n com esperança para todo filho seguidor, fiel e leal.',
      'Hey, avançar soldados unidos, \n O inimigo derrotar.\n Lado a lado a lutar e em frente marchar, marchar',
      'Baseados na obra de Deus, seremos soldados leais\n Marcharemos em união para a eternidade.\n O mais elevado padrão, de verdade e de bem\n Enfeitará os dias mais distantes de verdade e de amor',
      'Hey, avançar soldados unidos, \n O inimigo derrotar.\n Lado a lado a lutar e em frente marchar, marchar',
      'A nação nova oriental é além da imaginação.\n Pode transformar em sua luz toda a humanidade.\n A servir e a atender sempre aos Verdadeiros Pais\n e o mundo, então, irá conseguir a vitória muito\n esperada.',
      'Hey, avançar soldados unidos, \n O inimigo derrotar.\n Lado a lado a lutar e em frente marchar, marchar',
    ],
    SongsCategory.convivial,
    isSecondChorus: true,
  ),
  SongsModel(
    'UNIDADE (BRASIL)',
    '48',
    [
      'Arrebenta o elo de satã\n para além da terra e do mar\n E constrói um mundo para Deus\n cheio de alegria e de amor.\n Venham, povos de todo lugar, unidade buscar.\n É Seu grande sonho, para sempre,\n um país com a glória do Pai.',
      'Reunir, reunir,\n todo o povo se unir.\n Pra fazer uma nação unida,\n para se viver em paz.',
      'Faça um Forte pra defender a paz\n lá na nova Terra e no Céu.\n Cantaremos, “Aleluia”,\n junto no coração do Senhor.\n Venham, povos de todo lugar,\n unidade buscar.\n Repartindo amor e alegria\n como a Terra nunca viu igual.',
      'Reunir, reunir,\n todo o povo se unir.\n Pra fazer uma nação unida,\n para se viver em paz.',
    ],
    SongsCategory.convivial,
    isSecondChorus: true,
  ),
  SongsModel(
      'MINHA CRUZ (BRASIL)',
      '49',
      [
        'Oh! Quem pode me ajudar a cruz pesada levar?\n Mesmo antes de O conhecer, o Senhor me ajudou.\n Porque eu não tinha condição da carga suportar.\n Seu próprio sangue derramou para me resgatar.',
        'Marcharei com meu Senhor,\n E juro perseverar.\n Mais longe que Golgotá,\n Vitória chega já.',
        'Meu Pai nunca me deixará levar o peso da cruz.\n Seu sacrifício me livrou e a trilha se alargou.\n Me sacrifico para Ti e as provas vencerei.\n Dou minha vida para Ti e não vacilarei.',
        'Marcharei com meu Senhor,\n E juro perseverar.\n Mais longe que Golgotá,\n Vitória chega já.',
        'Meu Pai muito se esforçou para se aperfeiçoar.\n Se esforçamos, todos nós, podemos alcançar.\n Se não, os anos de sofrer, de nada servirão.\n Lutemos, pois, e ganharemos nosso galardão.',
        'Marcharei com meu Senhor,\n E juro perseverar.\n Mais longe que Golgotá,\n Vitória chega já.',
      ],
      SongsCategory.convivial,
      isSecondChorus: true),
  SongsModel(
    'A SONG OF THE BANQUET',
    '51',
    [
      'Pure new life that once was sown within the \ngarden\'s fertile soil,\n Sprouting seed has now become a blossom of \nheavenly loveliness.\n Father above, Lord of all, shower your blessing \nupon\n This holy day, bond of love forever more!\n Hallelujah, Glorious Day of Joy!',
      'Fairest flowers of the meadow, tender buds of \nperfect form.\n Now receive the gift of life and dance in the joy \nof eternal spring\n Heavenly host, men on earth, join us in praising \nthis day;\n Bless us to share, love\'s communion faithfully,\n Hallelujah, Glorious Day of Joy!',
      'Hushed we stand in awe before you, ready now to \ngive our pledge,\n To attend and serve completely with an unchanging \neternal love.\n Glorious King, mighty God, fill with your blessed \ngrace,\n This dearest one; holy banquet of our love.\n Hallelujah, Glorious Day of Joy!',
      'Overflowing with your love as dawn proclaims \neternal life,\n Earth and heaven come surround the glorious \nParents of mankind,\n Gather around, sing the song, fragrant the love \nof the Lord;\n Tell all the world, Spring has come eternally!\n Hallelujah, Glorious Day of Joy!',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'BLESSING OF GLORY',
    '52',
    [
      'Pure new life that once was sown within the garden\'s fertile soil,\n Sprouting seed has now become a blossom of heavenly loveliness.\n Father above, Lord of all, shower your blessing upon\n This holy day, bond of love forever more!\n Hallelujah, Glorious Day of Joy!',
      'Fairest flowers of the meadow, tender buds of perfect form.\n Now receive the gift of life and dance in the joy of eternal spring\n Heavenly host, men on earth, join us in praising this day;\n Bless us to share, love\'s communion faithfully,\n Hallelujah, Glorious Day of Joy!',
      'Hushed we stand in awe before you, ready now to give our pledge,\n To attend and serve completely with an unchanging eternal love.\n Glorious King, mighty God, fill with your blessed grace,\n This dearest one; holy banquet of our love.\n Hallelujah, Glorious Day of Joy!',
      'Overflowing with your love as dawn proclaims eternal life,\n Earth and heaven come surround the glorious Parents of mankind,\n Gather around, sing the song, fragrant the love of the Lord;\n Tell all the world, Spring has come eternally!\n Hallelujah, Glorious Day of Joy!',
    ],
    SongsCategory.english,
  ),
  SongsModel(
      'BY THE SPRING OF LIFE',
      '53',
      [
        'We\'re marching to the blessed land of Canaan with delight,\n We\'re leaving all our heavy burdens here.\n At last we are released and free from being slaves to sin,\n We\'re coming to the blessed spring of life.',
        'Coming to the spring where living water flows;\n In glory we\'ll be living evermore.\n Going to the land where freely flows the spring,\n In glory we\'ll be living evermore.',
        'O guide us with your pillars, Lord, of fire and of cloud,\n O give us paths to follow with our lives.\n The moment that we cross the Jordan River is at hand,\n We\'re coming to the blessed spring of life.',
        'Coming to the spring where living water flows;\n In glory we\'ll be living evermore.\n Going to the land where freely flows the spring,\n In glory we\'ll be living evermore.',
        'Our thirsting hearts receive with joy the manna from above,\n Your precious food will always be our strength\n So if the future finds us lacking we will not despair\n We\'re coming to the blessed spring of life.',
        'Coming to the spring where living water flows;\n In glory we\'ll be living evermore.\n Going to the land where freely flows the spring,\n In glory we\'ll be living evermore.',
      ],
      SongsCategory.english,
      isSecondChorus: true),
  SongsModel(
      'GRACE OF THE HOLY GARDEN',
      '54',
      [
        'Grace filling me with golden light, measureless blessing divine; \n God gives eternal life to me, perfect rejoicing is mine.',
        'Glorious the song ringing in my heart \n for my Father above; \n Gratefully I give, offering to Him, triumph and glorious love.',
        'Joy surging like an ocean wave, flowing so deep in my soul;\n Hope rises as I go in praise, knowing that man will be whole',
        'Glorious the song ringing in my heart \n for my Father above; \n Gratefully I give, offering to Him, triumph and glorious love.',
        'High, limitless eternal life, touching the top of the sky;\n Praise filling every part of me, blessing that never will die.',
        'Glorious the song ringing in my heart \n for my Father above; \n Gratefully I give, offering to Him, triumph and glorious love.',
        'You\'ve chosen me to do Your will, thankful, I vow to be true;\n I\'m pledging in my heart of hearts; Father, my life is for You.',
        'Glorious the song ringing in my heart \n for my Father above; \n Gratefully I give, offering to Him, triumph and glorious love.',
      ],
      SongsCategory.english,
      isSecondChorus: true),
  SongsModel(
    'HE HAS CALLED ME',
    '55',
    [
      'The Lord has called and I will go, where He leads me I will follow;\n The same in sorrow as in joy; with one heart I follow my Lord.\n For none on earth can turn me back, not even death can stop me,\n No none on earth can turn me back, not even death can stop me.',
      'To barren valleys piled with bones, I will take the living message;\n To Sodom\'s foul and wretched streets, I will bear the word with love.\n I bind my heart, my life to Yours, that it may be an offering,\n I bind my heart, my life to Yours, that it may be an offering.',
      'To You belongs our full acclaim, all glory power and honor,\n The world\'s contempt I do not fear, I will gladly bear the cross.\n Without esteem, without renown, I only wish to follow,\n Without esteem, without renown, I only wish to follow.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'HIGHER GROUND',
    '56',
    [
      'I\'m pressing on the upward way,\nNew heights I\'m gaining every day,\nStill praying as I\'m onward bound,\nLord, plant my feet on higher ground.',
      'Lord, lift me up and let me stand.\nBy faith on heaven\'s table land,\nA higher plane than I have found;\nLord, plant my feet on higher ground.',
      'My heart has no desire to stay\nWhere doubts arise and fears dismay,\nThough some may dwell where these abound,\nMy prayer, my aim is higher ground.',
      'Lord, lift me up and let me stand.\nBy faith on heaven\'s table land,\nA higher plane than I have found;\nLord, plant my feet on higher ground.',
      'I want to live above the world,\nThough Satan\'s darts at me are hurled,\nFor faith has caught the joyful sound,\nThe song of saints on higher ground.',
      'Lord, lift me up and let me stand.\nBy faith on heaven\'s table land,\nA higher plane than I have found;\nLord, plant my feet on higher ground.',
      'I want to scale the utmost height,\nAnd catch a gleam of glory bright,\nBut still I\'ll pray till heav\'n I\'ve found,\n \"Lord, lead me on to higher ground.\"',
      'Lord, lift me up and let me stand.\nBy faith on heaven\'s table land,\nA higher plane than I have found;\nLord, plant my feet on higher ground.',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'HOW GREAT THOU ART',
    '57',
    [
      'O Lord my God, when I in awesome wonder\n Consider all the works Your hands have made,\n I see the stars, I hear the rolling thunder,\n Your power throughout the universe displayed.',
      'Then sings my soul, my Savior God to Thee:\n How great Thou art, how great Thou art!\n This sings my soul, my Savior God, to Thee;\n How great Thou art, how great Thou art!',
      'When through the woods and forest glades I wander\n And hear the birds sing sweetly in the trees,\n When I look down from lofty mountain grandeur,\n And hear the brook and feel the gentle breeze.',
      'Then sings my soul, my Savior God to Thee:\n How great Thou art, how great Thou art!\n This sings my soul, my Savior God, to Thee;\n How great Thou art, how great Thou art!',
      'When Christ shall come with shout of acclamation\n And take me home, what joy shall fill my heart!\n Then I shall bow in humble adoration,\n And there proclaim, my God, how great Thou art',
      'Then sings my soul, my Savior God to Thee:\n How great Thou art, how great Thou art!\n This sings my soul, my Savior God, to Thee;\n How great Thou art, how great Thou art!',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'LIGHT OF GRACE',
    '58',
    [
      'O, Light of Grace, shining above,\n Lighting my dim shadowed way,\n O, Light of Grace, easing my pain,\n You have shown that God is love.',
      'I\'ll give my life, and my love, \n Unto the one God of love.',
      'Though clouds may come, hiding His face,\n Hiding the smile of my God,\n Though clouds may come,\n Still He is there,\n Shining brightly, Cod is love.',
      'I\'ll give my life, and my love, \n Unto the one God of love.',
      'Amid the storm, tossed on the sea,\n Beacon of hope, guiding me.\n Amid the storm, shelter is near,\n Trust in Him for God is love.',
      'I\'ll give my life, and my love, \n Unto the one God of love.',
      'All things decay, passing away,\n Only the light shall remain;\n All things decay; still there is One,\n True and faithful, God is love.',
      'I\'ll give my life, and my love, \n Unto the one God of love.',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'NEW SONG OF INSPIRATION',
    '59',
    [
      'Upon the earth I came to life in the world God prepared.\n One rejoicing land of freedom I am chosen to build,\n To reveal the Truth of God, His Purpose and His Will\n Sacrifice yourself and live all for His Desire, all for His Desire.',
      'All Heaven sings a mighty song, inspiration divine,\n For a new Eden begins now, spread the message to all.\n Sacrifice yourself to build, our Lord\'s new world of life.\n Seek the land of freedom now, all for His Desire, all for His Desire.',
      'We seek the new eternal base, blessed family of God, \n Long awaited by the Father, God of goodness above. \n Now proclaim the great new Truth, of kindness and good will. \n Pioneer new Heaven and earth all for His Desire, all for His Desire.',
      'Within a day of bright new life, stand upholding the right; \n In the pure new life eternal raise the standard of good. \n Praise the Father of all good, our glorious true ideal; \n Build a whole new world of peace, we will build it now, \n We will build it now.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'O COME, MY LORD',
    '60',
    [
      'O come my Lord; I beg You to come.\n O come to me and live within my heart;\n Come live in my heart so black and impure,\n That bears the burden of my sin.\n O come! My Lord, You are the fire that burns so bright;\n Come burn within my heart and cleans my sins,\n O how I pray that You will come soon;\n Come to me O Lord, Live within my heart.',
      'O come my Lord; I beg You to come.\n Come dwell with me my altar now awaits;\n O come to the altar waiting for you,\n But lost and hidden by the night.\n O come! My Lord, You are the light that fills the world;\n Come purify my altar by Your light.\n O how I pray that You will come soon;\n Many altars wait, Dwell with them, O Lord.',
      'O come my Lord; I beg You to come.\n O come and bring new life to all the earth;\n O come save the world from dying in pain;\n Restore our sinful world.\n O come! My Lord, You are the strength that will not change;\n Come end our evil ways and tragic times.\n O how I pray that You will come soon;\n Crying my heart, Come to us, O Lord.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'OUR FOREFATHERS',
    '61',
    [
      'Our forefathers built for us a beautiful land;\nTill it is completed, we will join in heart and hand.\nSee the new eternal history, beckoning us to come\nQuickly on the journey to the true eternal home.\nHow the beauty of our native land lifts us to the skies;\nGod has surely chosen this eternal paradise.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'PLEDGE',
    '62',
    [
      'My fallen figure shames the earth;\n Once I was born, yet never I lived,\n Never forsaking, You came to me\n Giving my life and breaking my chains\n Tenderly You gathered me up;\n Filled with love and sweating blood,\n Ever patient, You taught me the word,\n Carved in my heart, it forever remains.',
      'Never I knew what life should be;\n All I can do is follow your way.\n When on the path, I stumble and fall,\n Turning, You give the courage I need.\n Though the path is narrow and steep;\n Cruel thorns leave a trail of blood.\n Still I pledge I will follow the way,\n Follow as far as my Father will lead.',
      'Freed from a sleep so deep and dark,\n gladly I wake to knowing your will.\n Though death may stab me time and again,\n Nothing can change a loyal heart.\n This I pledge, my life is for You;\n For Your will I rush forward to die.\n This I pledge till the struggle is done,\n \'Till we proclaim the victorious day.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'SHINING FATHERLAND',
    '63',
    [
      'Sunlight beaming forth in the East, from the Fatherland;\n Bringing tidings of a new world to families in the field.\n Let us hasten to send the news all throughout the world,\n Eden\'s glory spreading forever the hope of joy and peace.',
      'Dawn, golden dawn, throughout the shining Fatherland,\n Tells the tidings of the rising sun that brings us life.',
      'Harvest quickly men of the fields, hasten to harvest now;\n Crops are ripened and ready to bring into the heavenly barn.\n Saints and angels and heavenly hosts gather to speed the task;\n All will share the harvest of joy at the banquet of our Lord.',
      'Dawn, golden dawn, throughout the shining Fatherland,\n Tells the tidings of the rising sun that brings us life.',
      'When the woes of six thousand years are gone from the Father\'s heart,\n Sons and daughters shall live with great joy, our True Parents\' own\n Saints and sages and men of good faith all waited for this day;\n Loyal men of hope and fidelity yearned to see this day.',
      'Dawn, golden dawn, throughout the shining Fatherland,\n Tells the tidings of the rising sun that brings us life.',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'SONG OF THE GARDEN',
    '64',
    [
      'The Lord into His garden comes;\n The spices yield a rich perfume;\n The lilies grow and thrive, the lilies grow and thrive.\n Refreshing showers of grace divine,\n From the Father flow to every vine,\n And make the dead revive, and make the dead revive.',
      'Oh that this dry and barren ground\n In springs of water may abound;\n A fruitful soil become, a fruitful soil become.\n The desert blossoms as the rose,\n When the Saviour conquers all his foes,\n And makes His people one, and makes His people one.',
      'Come brethren you that love the Lord,\n And taste the sweetness of His word;\n In Father\'s ways go on, in Father\'s ways go on,\n Our trouble and our trials here,\n Will only make us richer there,\n When we arrive at home, when we arrive at home.',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'SONG OF THE VICTORS',
    '65',
    [
      'Sing a loud Hosanna to the Lord,\n Offer everything with humble heart.\n Come attend the Lord, O rejoice in Him\n Who brings new life to all the world.\n Let us go determined to seek and find\n All the promised glory of the Lord (bis).',
      'There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.\n There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.',
      'There are clouds of darkness on the path,\n Sinful night enveloping the land.\n Brush the clouds aside and behold the \nlight\n That shines in beauty everywhere.\n Let us go determined to seek and find\n Our new world of joyfulness and peace (bis).',
      'There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.\n There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.',
      'Oh, my brothers all rejoice today,\n You who sing the song of our new life.\n Offer praise on high, blessed for \nevermore,\n As chosen people of the Lord.\n Let us go determined to seek and find\n All the brilliant glory of our dreams \n(bis).',
      'There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.\n There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.',
      'We uphold the standard of the Lord,\n To restore His true ideal.\n Freely give your love, share the Father\'s \njoy,\n And beauty will return to you.\n Let us go determined to seek and find\n Harmony within the Garden Bright (bis).',
      'There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.\n There we\'ll sing new songs in the Garden fair,\n Songs of freedom bright with happiness.',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'SONG OF THE VICTORY',
    '66',
    [
      'Sing Hosannas evermore!\n Sing of glory evermore!\n For the Lord has come again,\n Sing Hosannas evermore!',
      'Heaven dances at the sound,\n All His angels whirl around,\n All creation joining in,\n Dances at the joyful sound.',
      'See the new Jerusalem,\n Coming now upon the earth,\n For the day is here at last,\n Now the Lord has come at last.',
      'Brightly burn O Fire of Faith!\n Burn so brightly ev\'rywhere,\n Light of hope, burn today,\n Kindling ev\'ry faithful heart.\n',
      'Land of Egypt, land of woe,\n Waiting for the Lord\'s return.\n Soon the day will come at last,\n When the Rose of Sharon blooms.\n',
      'March along, march along,\n Have no fear, but march along;\n For you go to victory,\n Heaven\'s soldiers, march along.\n',
      'Praise the Lord, O praise the Lord!\n Praise the glorious Lord of all,\n To the Lord of truth and love,\n Sing to Him eternal praise.',
      'Sing Hosannas evermore!\n Sing of glory evermore!\n For the Lord has come again,\n Sing Hosannas evermore!\n',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'SPRING SONG OF EDEN',
    '67',
    [
      'Come O ye friends to the Garden of Eden, where \nthe spring blossoms are best;\n Joyfully singing together our song, Friends in \nour Eden regained,\n Here in the Garden together we\'ll meet, Singing \nnew songs of joy.\n',
      'Come, O ye friends, to the Garden of Eden, \nSinging new songs of delight;\n Joyfully dancing together with song, Friends in \nour Eden rejoice,\n Here in the Garden together we\'ll dance, Singing \nnew songs of joy.\n',
      'Come, O ye friends, to the Garden of Eden, Where \njoy and happiness reign;\n Joyfully sharing together our love, Here in the \ngarden of peace;\n Come, ye, O come to the Garden my friends, \nSinging new songs of joy.\n',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'TAN SHIM GA',
    '68',
    [
      'I mo mi ju go do ju go\n Il bek pon go jo ju go\n Beg gol ri jin to de yo\n Nok shi ra do i ko ob ko\n Im Hyung han il pyun tan shim Ka sil chul li issu rya\n Im hyung han il pyun tan shim Ka sil chul li issu rya.\n',
      'Although my body perishes\n And yet one thousand times dies\n My bones become ashes\n Even my soul vanishes\n Still all my love and all my heart\n Unchanging remain with you\n My everlasting loyalty\n Unchanging remains with you.\n',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'THE FATHER\'S DWELLING PLACE',
    '69',
    [
      'The Father\'s dwelling place is the fountain of our life,\n Drawn to the light of eternal day, we abandon the darkness.\n May the Word of God in my heart resound\n So eternally, to receive His love.\n We shall be His pride and delight, children of the Living God.\n Into the world of Eden regained, Let\'s go marching together.\n',
      'The Father\'s dwelling place is the throne of new life,\n Now our resurrection is come, which we long awaited.\n May the Word of God, in my heart resound,\n So eternally, to receive His joy.\n We shall be His pride and delight, children of the Living God,\n Into the world of Eden regained, Let\'s go singing together.\n',
      'The Father\'s dwelling place is the eternal paradise,\n Where the blessing He had to reserve will be freely given.\n May the Word of God in my heart resound,\n So eternally to receive His praise.\n We shall be His pride and delight, children of the Living God,\n Into the world of Eden regained, Let\'s go dancing together!\n',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'THE PRINCIPLE YOUTH MARCH',
    '70',
    [
      'We are the youth, soldiers of the truth, called by our God on high;\n Now is the time, march to the world, sounding the battle cry!\n Too long the dark night of sin held in fear the people of the world,\n We\'ll drive the darkness away, bringing in the new day.\n',
      'Lift high! Lift high! The banner of Truth on high;\n March forward crossing the sea, to the ends of the earth.\n',
      'Heaven and earth all are made anew, blessed by the light of God;\n Evil and sin vanish away, burned in the holy fire.\n This is the land of the heart, every people living as one,\n Glad voices filling the land, sing a joyful song.\n',
      'Lift high! Lift high! The banner of Truth on high;\n March forward crossing the sea, to the ends of the earth.\n',
      'Proud is my heart bursting with my hope, we are the youth of God;\n See how we go moving as one, marching at His command.\n Five colors shine in the ranks, every people, every race of man.\n We\'ll shake the heavens and earth, with our victory song.\n',
      'Lift high! Lift high! The banner of Truth on high;\n March forward crossing the sea, to the ends of the earth.\n',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'UNIFIED SOLDIERS',
    '71',
    [
      'Strong bond of heart is the force bringing the world into life,\n Joined in a kinship of love, all shall live as one.\n Here in the home of our hearts, we\'ll share evermore.\n On this foundation of happiness, we shall live forever.\n',
      'We\'re His pride in the heavenly war,\n Unified soldiers! Mightily, with one accord,\n We shall march, we shall march on!\n',
      'True men of boundless domain, Magnifying their light,\n Glorious beacons of truth, o\'er all things of the earth.\n From that original word life will spring and grow;\n In its expression it gives to all the fulfillment of hope.\n',
      'We\'re His pride in the heavenly war,\n Unified soldiers! Mightily, His will to do,\n We shall march, we shall march on!\n',
      'Based on the order of God, We\'ll build truthfulness,\n One constant value that gives pledge of eternity.\n The highest standard of truth which is raised above,\n Will decorate far distant days of radiant goodness.\n',
      'We\'re His price in the heavenly war,\n Unified soldiers! Mightily, proclaiming,\n We shall march, we shall march on!\n',
      'New culture dawns in the East, Glorious beyond our dreams.\n Mankind transformed in its light, shall be one family.\n Ever to serve and attend our True Parents\' own,\n Without a doubt the world shall be one world of victory.\n',
      'We\'re His pride in the heavenly war,\n Unified soldiers! Mightily, into that ideal,\n We shall march, we shall march on!\n',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'UNITE INTO ONE',
    '72',
    [
      'Chase away the power of Satan, far away beyond the land and sea;\n Build for God a boundless Kingdom, giving joy and liberty to all.\n Come, ye people all around the world, let\'s unit into one;\n Spreading forth the glory of the Father, and His great will forevermore.\n',
      'Unite, Unite, let\'s unite into one\n Bring about one nation uniting all the people of the world.\n',
      'Raise the white cross on our banner, high upon Mt. Everest it waves;\n In the blue Pacific waters, cleanse the sword that brought the victory.\n Come, ye people all around the world, let\'s unite into one.\n Now resolve to end the deep resentment, of the long centuries past\n',
      'Unite, Unite, let\'s unite into one\n Bring about one nation uniting all the people of the world.\n',
      'Build a fortress to defend the peace, on the great new heaven and new \nearth;\n We will all sing \'Hallelujah,\' safe within the bosom of the Lord.\n Come, ye people all around the world, let\'s unite into one.\n Share the joy and glory of Heaven, hidden so long from every eye.\n',
      'Unite, Unite, let\'s unite into one\n Bring about one nation uniting all the people of the world.\n',
    ],
    SongsCategory.english,
    isSecondChorus: true,
  ),
  SongsModel(
    'WHEN I BEHOLD THE LORD',
    '73',
    [
      'When I behold the Lord of all, my old self dies away.\n So dies the world of sinfulness giving birth to good.\n Soon a new self emerges, clear and bright and pure;\n Come and behold the new life, heaven and earth reborn.\n',
      'Now I behold Jerusalem, city of loveliness,\n Gently descending from above, ever to be my own.\n Joy never ending is with me, long as the Lord is near;\n Joy ever flows in sweetness, river of precious life.\n',
      'Kingdom of God eternal fervently I desired;\n heavenly rays so softy fall, shining the Sun of Grace.\n Springing forth in ripeness, fruit of the Tree of Life,\n Torment of doubt is over, gone is the shadow of death.\n',
      'Torturing every part of me, sinfulness rules my soul.\n Still God can raise me purified, giving creation to me.\n Letting me live in his palace, shining with golden light;\n Boundless His love and kindness, boundless His love for me!\n',
    ],
    SongsCategory.english,
  ),
  SongsModel(
    'SARANG HAE',
    '117',
    [
      'Sarang hae tan si nul,\n tchong mallo sarang hae.\n Tan shin ni nae kgyo tul,\n to na ghan dwi-eh.\n Olmana nun mul ul,\n hul ryun nun jchi morin-dao.',
      'Ye Ye Ye, Ye Ye Ye, etc…\n Sarang hae tan shi nul, chong mallo sarang hae.',
      'Molida na bo rin,\n mo ni jchul kude-o.\n Tan shini nae hgyo tul,\n To na ghanidwi-eh.\n Pam mada guinun,\n Bogo shi pun nae sa rang-ah.',
      'Ye Ye Ye, Ye Ye Ye, etc…\n Pam mada guinun, bogo shi pun nae sa rang-ah.',
    ],
    SongsCategory.international,
    isSecondChorus: true,
    musicTrackPath: 'assets/SARANG-HAE.mp3',
  ),
];

enum SongsCategory { holy, convivial, english, international }
