import 'package:ffpmupt/settings/app_language.dart';
import 'package:flutter/widgets.dart';

String adminText(BuildContext context, String portuguese) {
  final language =
      AppLanguageScope.maybeWatch(context)?.language ?? AppLanguage.portuguese;
  if (language == AppLanguage.portuguese || language == AppLanguage.brazilian) {
    return portuguese;
  }
  return _english[portuguese] ?? portuguese;
}

const _english = <String, String>{
  'Adicionar Holy Ground': 'Add Holy Ground',
  'Novo local': 'New place',
  'Editar': 'Edit',
  'Novo Holy Ground': 'New Holy Ground',
  'Editar Holy Ground': 'Edit Holy Ground',
  'Guardar': 'Save',
  'Identificação': 'Identification',
  'Nome': 'Name',
  'Cidade': 'City',
  'Endereço completo': 'Full address',
  'Latitude (opcional)': 'Latitude (optional)',
  'Longitude (opcional)': 'Longitude (optional)',
  'Fotografia': 'Photo',
  'Selecionar fotografia': 'Select photo',
  'Trocar fotografia': 'Replace photo',
  'Remover': 'Remove',
  'JPG, PNG ou WebP, até 5 MB.': 'JPG, PNG or WebP, up to 5 MB.',
  'Conteúdo': 'Content',
  'Resumo': 'Summary',
  'História': 'History',
  'Instruções de visita': 'Visit instructions',
  'Contato e publicação': 'Contact and publishing',
  'Responsável': 'Contact person',
  'Email de contato': 'Contact email',
  'Idioma': 'Language',
  'Ordem': 'Order',
  'Local visível no diretório': 'Place visible in directory',
  'Guardar Holy Ground': 'Save Holy Ground',
  'Campo obrigatório': 'Required field',
  'Coordenada inválida': 'Invalid coordinate',
  'Use uma imagem JPG, PNG ou WebP.': 'Use a JPG, PNG or WebP image.',
  'A fotografia deve ter no máximo 5 MB.': 'The photo must be 5 MB or smaller.',
  'Não foi possível ler a fotografia selecionada.':
      'The selected photo could not be read.',
  'Preencha latitude e longitude juntas.':
      'Enter latitude and longitude together.',
  'Confira os limites da latitude e longitude.':
      'Check the latitude and longitude limits.',
  'Selecione uma fotografia antes de publicar o local.':
      'Select a photo before publishing the place.',
  'Guardando dados...': 'Saving data...',
  'Enviando fotografia...': 'Uploading photo...',
  'Publicado': 'Published',
  'Oculto': 'Hidden',
  'Local publicado no diretório.': 'Place published in the directory.',
  'Local ocultado do diretório.': 'Place hidden from the directory.',
  'Não foi possível alterar a publicação.':
      'The publishing status could not be changed.',
  'Email inválido': 'Invalid email',
  'Use um número inteiro': 'Use a whole number',
  'Nova música': 'New song',
  'Gestão de músicas': 'Song management',
  'Pesquisar música ou página': 'Search song or page',
  'Modelo XLSX': 'XLSX template',
  'Catálogo padrão': 'Default catalog',
  'Importar XLSX/PPTX': 'Import XLSX/PPTX',
  'Informação': 'Information',
  'Título': 'Title',
  'Página': 'Page',
  'Categoria': 'Category',
  'Cânticos Sagrados': 'Holy Songs',
  'Convívio': 'Fellowship',
  'Inglês': 'English',
  'Adoração': 'Worship',
  'Internacional': 'International',
  'Música ativa': 'Song active',
  'Versos': 'Verses',
  'Adicionar verso': 'Add verse',
  'Remover verso': 'Remove verse',
  'Refrão': 'Chorus',
  'Nenhum': 'None',
  'Versos ímpares': 'Odd verses',
  'Versos pares': 'Even verses',
  'Áudios': 'Audio tracks',
  'Adicionar áudio': 'Add audio',
  'Guardar música': 'Save song',
  'Nenhuma música reconhecida': 'No songs recognized',
  'Rever música': 'Review song',
  'Aplicar': 'Apply',
  'Rever importação': 'Review import',
  'Confirmar importação': 'Confirm import',
  'Remover áudio': 'Remove audio',
  'Caminho local ou URL': 'Local path or URL',
  'Inícios dos versos (segundos)': 'Verse starts (seconds)',
  'Mudanças de verso (segundos)': 'Verse changes (seconds)',
  'Áudio ativo': 'Audio active',
  'Nome do áudio': 'Audio name',
  'URL ou caminho do asset': 'URL or asset path',
  'Página de ofertas': 'Offering page',
  'Preencha o título de todos os métodos.': 'Enter a title for every method.',
  'Cada método ativo precisa de dados, link ou QR Code.':
      'Each active method needs details, a link or a QR Code.',
  'Dados de pagamento guardados.': 'Payment details saved.',
  'Texto introdutório': 'Introductory text',
  'Nota final (opcional)': 'Final note (optional)',
  'Página de pagamentos ativa': 'Payment page active',
  'Métodos de pagamento': 'Payment methods',
  'Adicionar método': 'Add method',
  'Adicione IBAN, PIX, MB Way, link de pagamento ou outro método.':
      'Add an IBAN, PIX, MB Way, payment link or another method.',
  'Novo método': 'New method',
  'Remover método': 'Remove method',
  'Tipo': 'Type',
  'Nome do método': 'Method name',
  'Ex.: Transferência bancária ou PIX': 'E.g. bank transfer or PIX',
  'Instruções (opcional)': 'Instructions (optional)',
  'Dados exibidos': 'Displayed details',
  'Adicionar dado': 'Add detail',
  'Rótulo': 'Label',
  'IBAN, Chave PIX, Nome...': 'IBAN, PIX key, Name...',
  'Valor': 'Value',
  'Remover dado': 'Remove detail',
  'Link de pagamento (opcional)': 'Payment link (optional)',
  'Conteúdo do QR Code (opcional)': 'QR Code content (optional)',
  'Cole o link ou payload completo fornecido pelo banco.':
      'Paste the full link or payload provided by the bank.',
  'Método ativo': 'Method active',
  'Transferência bancária': 'Bank transfer',
  'Link de pagamento': 'Payment link',
  'Outro': 'Other',
  'Preparar idiomas padrão': 'Prepare default languages',
  'Lema anual': 'Annual motto',
  'Este lema aparece na página pública deste país.':
      'This motto appears on this country’s public page.',
  'Texto do lema': 'Motto text',
  'Preencha o título e texto do lema.': 'Enter the motto title and text.',
  'Lema guardado.': 'Motto saved.',
  'Não foi possível guardar o lema.': 'Could not save the motto.',
  'Ainda não configurada': 'Not configured yet',
  'Preencha o título e os oito pontos.':
      'Enter the title and all eight points.',
  'Idioma visível': 'Language visible',
  'Guardar Promessa': 'Save Promise',
  'Ponto': 'Point',
  'Verso': 'Verse',
  'Convite de administrador': 'Administrator invitation',
  'Você foi convidado para administrar um país':
      'You were invited to manage a country',
  'Criar conta': 'Create account',
  'Já tenho conta': 'I already have an account',
  'Email que recebeu o convite': 'Email that received the invitation',
  'Senha': 'Password',
  'Confirmar senha': 'Confirm password',
  'Esqueci minha senha': 'I forgot my password',
  'Confirme seu email': 'Confirm your email',
  'Enviamos uma confirmação para': 'We sent a confirmation to',
  'Abra o email e depois volte aqui.': 'Open the email and then return here.',
  'Já confirmei': 'I have confirmed',
  'Reenviar confirmação': 'Resend confirmation',
  'Usar outra conta': 'Use another account',
  'Confirmar acesso administrativo': 'Confirm administrator access',
  'Países': 'Countries',
  'Aceitar convite': 'Accept invitation',
  'Acesso confirmado': 'Access confirmed',
  'Agora você pode selecionar o país e entrar na administração.':
      'You can now select the country and open the administration area.',
  'Continuar': 'Continue',
  'Entrar': 'Sign in',
  'Esta conta não corresponde ao email do convite.':
      'This account does not match the invitation email.',
  'Não foi possível abrir o convite.': 'The invitation could not be opened.',
  'Informe um email e uma senha com 8 caracteres.':
      'Enter an email and a password with at least 8 characters.',
  'As senhas não coincidem.': 'The passwords do not match.',
  'Email de confirmação enviado.': 'Confirmation email sent.',
  'Informe o email primeiro.': 'Enter the email first.',
  'Email para redefinir a senha enviado.': 'Password reset email sent.',
  'Este email já possui conta. Escolha “Já tenho conta”.':
      'This email already has an account. Choose “I already have an account”.',
  'Email ou senha incorretos.': 'Incorrect email or password.',
  'Email inválido.': 'Invalid email.',
  'Escolha uma senha mais forte.': 'Choose a stronger password.',
  'Muitas tentativas. Aguarde e tente novamente.':
      'Too many attempts. Wait and try again.',
  'Não foi possível autenticar.': 'Authentication failed.',
  'CRM operacional': 'Operations CRM',
  'Atualizar': 'Refresh',
  'Adicionar país': 'Add country',
  'País criado.': 'Country created.',
  'Não foi possível criar o país.': 'The country could not be created.',
  'Visão geral': 'Overview',
  'Prontos': 'Ready',
  'Igrejas': 'Churches',
  'Admins': 'Admins',
  'Novo país': 'New country',
  'Nenhum país encontrado.': 'No countries found.',
  'Configurações do país': 'Country settings',
  'País ativo': 'Country active',
  'Administrador associado': 'Administrator assigned',
  'Igreja local cadastrada': 'Local church registered',
  'Promessa nos idiomas necessários': 'Promise in the required languages',
  'Catálogo remoto preparado': 'Remote catalog prepared',
  'Pagamentos configurados': 'Payments configured',
  'Vídeos configurados': 'Videos configured',
  'Holy Grounds publicados': 'Holy Grounds published',
  'opcional': 'optional',
  'Prontidão do país': 'Country readiness',
  'Igrejas locais': 'Local churches',
  'Adicionar igreja': 'Add church',
  'Não foi possível carregar as igrejas.': 'The churches could not be loaded.',
  'Nenhuma igreja local cadastrada.': 'No local churches registered.',
  'Editar igreja': 'Edit church',
  'Administradores': 'Administrators',
  'Convidar administrador': 'Invite administrator',
  'Envie um link. O administrador cria e confirma a própria conta.':
      'Send a link. The administrator creates and confirms their own account.',
  'Não foi possível carregar os administradores.':
      'The administrators could not be loaded.',
  'Nenhum administrador associado.': 'No administrator assigned.',
  'Editar acesso': 'Edit access',
  'Pronto': 'Ready',
  'igrejas': 'churches',
  'músicas': 'songs',
  'Não foi possível carregar o CRM.': 'The CRM could not be loaded.',
  'Tentar novamente': 'Try again',
  'Código do país': 'Country code',
  'Idioma principal': 'Primary language',
  'Fuso horário IANA': 'IANA time zone',
  'Criar': 'Create',
  'Nova igreja': 'New church',
  'Nome da igreja': 'Church name',
  'Endereço': 'Address',
  'Fuso horário': 'Time zone',
  'Email do responsável': 'Contact person email',
  'Igreja ativa': 'Church active',
  'Não foi possível guardar': 'Could not save',
  'Editar administrador': 'Edit administrator',
  'Administrador ativo': 'Administrator active',
  'Remover deste país': 'Remove from this country',
  'Convites pendentes': 'Pending invitations',
  'Copiar link': 'Copy link',
  'Cancelar convite': 'Cancel invitation',
  'Criar convite': 'Create invitation',
  'Convite criado': 'Invitation created',
  'Envie este link para': 'Send this link to',
  'Link copiado.': 'Link copied.',
  'Não foi possível criar o convite': 'Could not create the invitation',
  'Cancelar': 'Cancel',
  'Fechar': 'Close',
};
