import 'package:ffpmupt/settings/app_language.dart';

class AppStrings {
  const AppStrings({
    required this.sundayService,
    required this.homeSubtitle,
    required this.appLanguage,
    required this.songs,
    required this.songsSubtitle,
    required this.familyPromise,
    required this.familyPromiseSubtitle,
    required this.promiseHistoryLabel,
    required this.motto,
    required this.mottoSubtitle,
    required this.offerings,
    required this.offeringsSubtitle,
    required this.weeklyVideos,
    required this.weeklyVideosSubtitle,
    required this.copyVideoLink,
    required this.videoLinkCopied,
    required this.updateVideoLinks,
    required this.updateVideoLinksSubtitle,
    required this.youtubeVideoLink,
    required this.vimeoVideoLink,
    required this.saveVideoLinks,
    required this.videoLinksSaved,
    required this.videoLinksSavedLocally,
    required this.invalidVideoLink,
    required this.adminLogin,
    required this.adminEmail,
    required this.password,
    required this.signIn,
    required this.signOut,
    required this.cancel,
    required this.togglePasswordVisibility,
    required this.adminAccessDenied,
    required this.signInFailed,
    required this.adminArea,
    required this.adminDashboard,
    required this.countrySettings,
    required this.countrySettingsSubtitle,
    required this.countryCode,
    required this.countryName,
    required this.defaultLanguage,
    required this.timezone,
    required this.countryEnabled,
    required this.save,
    required this.countrySaved,
    required this.countrySaveFailed,
    required this.searchSongHint,
    required this.clearSearch,
    required this.searchByTitlePageLyrics,
    required this.all,
    required this.withMusic,
    required this.noSongsFound,
    required this.page,
    required this.songCountSuffix,
    required this.holySongs,
    required this.convivialSongs,
    required this.englishSongs,
    required this.worshipSongs,
    required this.internationalSongs,
    required this.audioAvailable,
    required this.previousLyric,
    required this.nextLyric,
    required this.increaseTextSize,
    required this.decreaseTextSize,
    required this.verse,
    required this.markAsUsed,
    required this.resetHistory,
    required this.readAloud,
    required this.stopReading,
    required this.offeringTransfer,
    required this.paymentQr,
    required this.paymentQrInstruction,
    required this.bankDetails,
    required this.name,
    required this.copyIban,
    required this.ibanCopied,
    required this.publicOfferingSubtitle,
    required this.iban,
    required this.bank,
    required this.description,
    required this.offeringQrNote,
    required this.configureOfferingQr,
  });

  final String sundayService;
  final String homeSubtitle;
  final String appLanguage;
  final String songs;
  final String songsSubtitle;
  final String familyPromise;
  final String familyPromiseSubtitle;
  final String promiseHistoryLabel;
  final String motto;
  final String mottoSubtitle;
  final String offerings;
  final String offeringsSubtitle;
  final String weeklyVideos;
  final String weeklyVideosSubtitle;
  final String copyVideoLink;
  final String videoLinkCopied;
  final String updateVideoLinks;
  final String updateVideoLinksSubtitle;
  final String youtubeVideoLink;
  final String vimeoVideoLink;
  final String saveVideoLinks;
  final String videoLinksSaved;
  final String videoLinksSavedLocally;
  final String invalidVideoLink;
  final String adminLogin;
  final String adminEmail;
  final String password;
  final String signIn;
  final String signOut;
  final String cancel;
  final String togglePasswordVisibility;
  final String adminAccessDenied;
  final String signInFailed;
  final String adminArea;
  final String adminDashboard;
  final String countrySettings;
  final String countrySettingsSubtitle;
  final String countryCode;
  final String countryName;
  final String defaultLanguage;
  final String timezone;
  final String countryEnabled;
  final String save;
  final String countrySaved;
  final String countrySaveFailed;
  final String searchSongHint;
  final String clearSearch;
  final String searchByTitlePageLyrics;
  final String all;
  final String withMusic;
  final String noSongsFound;
  final String page;
  final String songCountSuffix;
  final String holySongs;
  final String convivialSongs;
  final String englishSongs;
  final String worshipSongs;
  final String internationalSongs;
  final String audioAvailable;
  final String previousLyric;
  final String nextLyric;
  final String increaseTextSize;
  final String decreaseTextSize;
  final String verse;
  final String markAsUsed;
  final String resetHistory;
  final String readAloud;
  final String stopReading;
  final String offeringTransfer;
  final String paymentQr;
  final String paymentQrInstruction;
  final String bankDetails;
  final String name;
  final String copyIban;
  final String ibanCopied;
  final String publicOfferingSubtitle;
  final String iban;
  final String bank;
  final String description;
  final String offeringQrNote;
  final String configureOfferingQr;

  static AppStrings of(AppLanguage language) {
    switch (language) {
      case AppLanguage.portuguese:
        return portuguese;
      case AppLanguage.korean:
        return korean;
      case AppLanguage.english:
        return english;
      case AppLanguage.spanish:
        return spanish;
      case AppLanguage.german:
        return german;
      case AppLanguage.italian:
        return italian;
      case AppLanguage.french:
        return french;
    }
  }

  static const portuguese = AppStrings(
    sundayService: 'Serviço de Domingo',
    homeSubtitle: 'Textos e canções para a comunidade FFPMU Portugal',
    appLanguage: 'Idioma da app',
    songs: 'Canções',
    songsSubtitle: 'Letras, páginas e áudio disponível',
    familyPromise: 'Promessa da Família',
    familyPromiseSubtitle: 'Leitura, histórico e voz',
    promiseHistoryLabel: 'Promessa',
    motto: 'Lema 2026',
    mottoSubtitle: 'Texto anual para ler e projetar',
    offerings: 'Ofertas / Dízimos',
    offeringsSubtitle: 'IBAN copiável e QR para abrir no telemóvel',
    weeklyVideos: 'Vídeos / Semanário',
    weeklyVideosSubtitle: 'Últimos vídeos semanais do YouTube e Vimeo',
    copyVideoLink: 'Copiar link do vídeo',
    videoLinkCopied: 'Link do vídeo copiado',
    updateVideoLinks: 'Atualizar links dos vídeos',
    updateVideoLinksSubtitle: 'Cole os links novos do YouTube e do Vimeo',
    youtubeVideoLink: 'Link do YouTube',
    vimeoVideoLink: 'Link do Vimeo',
    saveVideoLinks: 'Guardar links',
    videoLinksSaved: 'Links dos vídeos guardados',
    videoLinksSavedLocally:
        'Links guardados apenas neste dispositivo. Verifique as regras do Firestore.',
    invalidVideoLink: 'Confira os links do YouTube e Vimeo',
    adminLogin: 'Entrar como administrador',
    adminEmail: 'Email do administrador',
    password: 'Palavra-passe',
    signIn: 'Entrar',
    signOut: 'Terminar sessão',
    cancel: 'Cancelar',
    togglePasswordVisibility: 'Mostrar ou ocultar palavra-passe',
    adminAccessDenied: 'Esta conta não tem acesso de administrador',
    signInFailed: 'Não foi possível entrar. Confira email e palavra-passe.',
    adminArea: 'Administração',
    adminDashboard: 'Gestão de conteúdo',
    countrySettings: 'Configuração do país',
    countrySettingsSubtitle: 'Nome, idioma, timezone e estado de Portugal',
    countryCode: 'Código do país',
    countryName: 'Nome do país',
    defaultLanguage: 'Idioma padrão',
    timezone: 'Timezone',
    countryEnabled: 'País ativo',
    save: 'Guardar',
    countrySaved: 'Configuração do país guardada',
    countrySaveFailed: 'Não foi possível guardar no Firestore',
    searchSongHint: 'Pesquise aqui uma canção',
    clearSearch: 'Limpar pesquisa',
    searchByTitlePageLyrics: 'Título, página ou letra',
    all: 'Todos',
    withMusic: 'Com música',
    noSongsFound: 'Nenhuma canção encontrada',
    page: 'Página',
    songCountSuffix: 'canções',
    holySongs: 'Cânticos Sagrados',
    convivialSongs: 'Canções de Convívio',
    englishSongs: 'Holy Songs',
    worshipSongs: 'Worship Songs',
    internationalSongs: 'Canções Internacionais',
    audioAvailable: 'Áudio disponível',
    previousLyric: 'Estrofe anterior',
    nextLyric: 'Estrofe seguinte',
    increaseTextSize: 'Aumentar letra',
    decreaseTextSize: 'Diminuir letra',
    verse: 'Estrofe',
    markAsUsed: 'Marcar como usada',
    resetHistory: 'Limpar histórico',
    readAloud: 'Ler em voz alta',
    stopReading: 'Parar leitura',
    offeringTransfer: 'Transferência bancária',
    paymentQr: 'QR para pagamento',
    paymentQrInstruction:
        'Leia para abrir a página de ofertas e copiar o IBAN.',
    bankDetails: 'Dados de pagamento',
    name: 'Nome',
    copyIban: 'Copiar IBAN',
    ibanCopied: 'IBAN copiado',
    publicOfferingSubtitle:
        'Copie o IBAN e faça a transferência na app do banco.',
    iban: 'IBAN',
    bank: 'Banco',
    description: 'Descrição',
    offeringQrNote:
        'Nota: este QR abre uma página simples do site com o IBAN para copiar. Depois, faça a transferência na sua app bancária.',
    configureOfferingQr:
        'Configure offeringPageUrl em lib/content/offering.dart para ativar o QR.',
  );

  static const korean = AppStrings(
    sundayService: '주일 예배',
    homeSubtitle: 'FFPMU 포르투갈 공동체를 위한 말씀과 성가',
    appLanguage: '앱 언어',
    songs: '성가',
    songsSubtitle: '가사, 페이지 및 사용 가능한 오디오',
    familyPromise: '가정맹세',
    familyPromiseSubtitle: '낭독, 기록 및 음성',
    promiseHistoryLabel: '맹세',
    motto: '2026년 표어',
    mottoSubtitle: '읽고 투사할 연간 표어',
    offerings: '헌금 / 십일조',
    offeringsSubtitle: '복사 가능한 IBAN 및 모바일용 QR',
    weeklyVideos: '영상 / 주간 뉴스',
    weeklyVideosSubtitle: 'YouTube 및 Vimeo 최신 주간 영상',
    copyVideoLink: '영상 링크 복사',
    videoLinkCopied: '영상 링크가 복사되었습니다',
    updateVideoLinks: '영상 링크 업데이트',
    updateVideoLinksSubtitle: '새 YouTube 및 Vimeo 링크를 붙여넣으세요',
    youtubeVideoLink: 'YouTube 링크',
    vimeoVideoLink: 'Vimeo 링크',
    saveVideoLinks: '링크 저장',
    videoLinksSaved: '영상 링크가 저장되었습니다',
    videoLinksSavedLocally: '링크가 이 기기에만 저장되었습니다. Firestore 규칙을 확인하세요.',
    invalidVideoLink: 'YouTube 및 Vimeo 링크를 확인하세요',
    adminLogin: '관리자로 로그인',
    adminEmail: '관리자 이메일',
    password: '비밀번호',
    signIn: '로그인',
    signOut: '로그아웃',
    cancel: '취소',
    togglePasswordVisibility: '비밀번호 표시 또는 숨기기',
    adminAccessDenied: '이 계정에는 관리자 권한이 없습니다',
    signInFailed: '로그인할 수 없습니다. 이메일과 비밀번호를 확인하세요.',
    adminArea: '관리',
    adminDashboard: '콘텐츠 관리',
    countrySettings: '국가 설정',
    countrySettingsSubtitle: '포르투갈의 이름, 언어, 시간대 및 상태',
    countryCode: '국가 코드',
    countryName: '국가명',
    defaultLanguage: '기본 언어',
    timezone: '시간대',
    countryEnabled: '국가 활성화',
    save: '저장',
    countrySaved: '국가 설정이 저장되었습니다',
    countrySaveFailed: 'Firestore에 저장할 수 없습니다',
    searchSongHint: '성가를 검색하세요',
    clearSearch: '검색 지우기',
    searchByTitlePageLyrics: '제목, 페이지 또는 가사',
    all: '전체',
    withMusic: '음악 있음',
    noSongsFound: '성가를 찾을 수 없습니다',
    page: '페이지',
    songCountSuffix: '곡',
    holySongs: '성가',
    convivialSongs: '친교 노래',
    englishSongs: '영어 성가',
    worshipSongs: '찬양',
    internationalSongs: '국제 노래',
    audioAvailable: '오디오 있음',
    previousLyric: '이전 절',
    nextLyric: '다음 절',
    increaseTextSize: '글자 크게',
    decreaseTextSize: '글자 작게',
    verse: '절',
    markAsUsed: '사용 기록에 추가',
    resetHistory: '기록 지우기',
    readAloud: '소리내어 읽기',
    stopReading: '읽기 중지',
    offeringTransfer: '은행 송금',
    paymentQr: '결제 QR',
    paymentQrInstruction: '헌금 페이지를 열어 IBAN을 복사하려면 스캔하세요.',
    bankDetails: '결제 정보',
    name: '이름',
    copyIban: 'IBAN 복사',
    ibanCopied: 'IBAN이 복사되었습니다',
    publicOfferingSubtitle: 'IBAN을 복사한 뒤 은행 앱에서 송금하세요.',
    iban: 'IBAN',
    bank: '은행',
    description: '설명',
    offeringQrNote:
        '참고: 이 QR은 IBAN을 복사할 수 있는 간단한 헌금 페이지를 엽니다. 이후 은행 앱에서 송금하세요.',
    configureOfferingQr:
        'QR을 활성화하려면 lib/content/offering.dart에서 offeringPageUrl을 설정하세요.',
  );

  static const english = AppStrings(
    sundayService: 'Sunday Service',
    homeSubtitle: 'Texts and songs for the FFPMU Portugal community',
    appLanguage: 'App language',
    songs: 'Songs',
    songsSubtitle: 'Lyrics, pages, and available audio',
    familyPromise: 'Family Pledge',
    familyPromiseSubtitle: 'Reading, history, and voice',
    promiseHistoryLabel: 'Pledge',
    motto: '2026 Motto',
    mottoSubtitle: 'Annual text for reading and projection',
    offerings: 'Offerings / Tithes',
    offeringsSubtitle: 'Copyable IBAN and phone QR',
    weeklyVideos: 'Videos / Weekly News',
    weeklyVideosSubtitle: 'Latest weekly videos from YouTube and Vimeo',
    copyVideoLink: 'Copy video link',
    videoLinkCopied: 'Video link copied',
    updateVideoLinks: 'Update video links',
    updateVideoLinksSubtitle: 'Paste the new YouTube and Vimeo links',
    youtubeVideoLink: 'YouTube link',
    vimeoVideoLink: 'Vimeo link',
    saveVideoLinks: 'Save links',
    videoLinksSaved: 'Video links saved',
    videoLinksSavedLocally:
        'Links saved on this device only. Check the Firestore rules.',
    invalidVideoLink: 'Check the YouTube and Vimeo links',
    adminLogin: 'Admin login',
    adminEmail: 'Admin email',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    cancel: 'Cancel',
    togglePasswordVisibility: 'Show or hide password',
    adminAccessDenied: 'This account does not have admin access',
    signInFailed: 'Could not sign in. Check the email and password.',
    adminArea: 'Administration',
    adminDashboard: 'Content management',
    countrySettings: 'Country settings',
    countrySettingsSubtitle: 'Portugal name, language, timezone, and status',
    countryCode: 'Country code',
    countryName: 'Country name',
    defaultLanguage: 'Default language',
    timezone: 'Timezone',
    countryEnabled: 'Country enabled',
    save: 'Save',
    countrySaved: 'Country settings saved',
    countrySaveFailed: 'Could not save to Firestore',
    searchSongHint: 'Search for a song',
    clearSearch: 'Clear search',
    searchByTitlePageLyrics: 'Title, page, or lyrics',
    all: 'All',
    withMusic: 'With music',
    noSongsFound: 'No songs found',
    page: 'Page',
    songCountSuffix: 'songs',
    holySongs: 'Holy Songs',
    convivialSongs: 'Fellowship Songs',
    englishSongs: 'English Songs',
    worshipSongs: 'Worship Songs',
    internationalSongs: 'International Songs',
    audioAvailable: 'Audio available',
    previousLyric: 'Previous verse',
    nextLyric: 'Next verse',
    increaseTextSize: 'Increase text size',
    decreaseTextSize: 'Decrease text size',
    verse: 'Verse',
    markAsUsed: 'Mark as used',
    resetHistory: 'Clear history',
    readAloud: 'Read aloud',
    stopReading: 'Stop reading',
    offeringTransfer: 'Bank transfer',
    paymentQr: 'Payment QR',
    paymentQrInstruction: 'Scan to open the offering page and copy the IBAN.',
    bankDetails: 'Payment details',
    name: 'Name',
    copyIban: 'Copy IBAN',
    ibanCopied: 'IBAN copied',
    publicOfferingSubtitle:
        'Copy the IBAN and make the transfer in your banking app.',
    iban: 'IBAN',
    bank: 'Bank',
    description: 'Description',
    offeringQrNote:
        'Note: this QR opens a simple website page with the IBAN to copy. Then make the transfer in your banking app.',
    configureOfferingQr:
        'Configure offeringPageUrl in lib/content/offering.dart to activate the QR.',
  );

  static const spanish = AppStrings(
    sundayService: 'Servicio dominical',
    homeSubtitle: 'Textos y canciones para la comunidad FFPMU Portugal',
    appLanguage: 'Idioma de la app',
    songs: 'Canciones',
    songsSubtitle: 'Letras, páginas y audio disponible',
    familyPromise: 'Promesa de la Familia',
    familyPromiseSubtitle: 'Lectura, historial y voz',
    promiseHistoryLabel: 'Promesa',
    motto: 'Lema 2026',
    mottoSubtitle: 'Texto anual para leer y proyectar',
    offerings: 'Ofrendas / Diezmos',
    offeringsSubtitle: 'IBAN copiable y QR para el móvil',
    weeklyVideos: 'Vídeos / Semanario',
    weeklyVideosSubtitle: 'Últimos vídeos semanales de YouTube y Vimeo',
    copyVideoLink: 'Copiar enlace del vídeo',
    videoLinkCopied: 'Enlace del vídeo copiado',
    updateVideoLinks: 'Actualizar enlaces de vídeos',
    updateVideoLinksSubtitle: 'Pega los nuevos enlaces de YouTube y Vimeo',
    youtubeVideoLink: 'Enlace de YouTube',
    vimeoVideoLink: 'Enlace de Vimeo',
    saveVideoLinks: 'Guardar enlaces',
    videoLinksSaved: 'Enlaces de vídeos guardados',
    videoLinksSavedLocally:
        'Enlaces guardados solo en este dispositivo. Revisa las reglas de Firestore.',
    invalidVideoLink: 'Revisa los enlaces de YouTube y Vimeo',
    adminLogin: 'Acceso de administrador',
    adminEmail: 'Email del administrador',
    password: 'Contraseña',
    signIn: 'Entrar',
    signOut: 'Cerrar sesión',
    cancel: 'Cancelar',
    togglePasswordVisibility: 'Mostrar u ocultar contraseña',
    adminAccessDenied: 'Esta cuenta no tiene acceso de administrador',
    signInFailed: 'No se pudo entrar. Revisa el email y la contraseña.',
    adminArea: 'Administración',
    adminDashboard: 'Gestión de contenido',
    countrySettings: 'Configuración del país',
    countrySettingsSubtitle:
        'Nombre, idioma, zona horaria y estado de Portugal',
    countryCode: 'Código del país',
    countryName: 'Nombre del país',
    defaultLanguage: 'Idioma predeterminado',
    timezone: 'Zona horaria',
    countryEnabled: 'País activo',
    save: 'Guardar',
    countrySaved: 'Configuración del país guardada',
    countrySaveFailed: 'No se pudo guardar en Firestore',
    searchSongHint: 'Busca una canción',
    clearSearch: 'Limpiar búsqueda',
    searchByTitlePageLyrics: 'Título, página o letra',
    all: 'Todo',
    withMusic: 'Con música',
    noSongsFound: 'No se encontraron canciones',
    page: 'Página',
    songCountSuffix: 'canciones',
    holySongs: 'Cantos sagrados',
    convivialSongs: 'Canciones de convivencia',
    englishSongs: 'Canciones en inglés',
    worshipSongs: 'Canciones de adoración',
    internationalSongs: 'Canciones internacionales',
    audioAvailable: 'Audio disponible',
    previousLyric: 'Estrofa anterior',
    nextLyric: 'Estrofa siguiente',
    increaseTextSize: 'Aumentar texto',
    decreaseTextSize: 'Reducir texto',
    verse: 'Estrofa',
    markAsUsed: 'Marcar como usada',
    resetHistory: 'Limpiar historial',
    readAloud: 'Leer en voz alta',
    stopReading: 'Detener lectura',
    offeringTransfer: 'Transferencia bancaria',
    paymentQr: 'QR de pago',
    paymentQrInstruction:
        'Escanea para abrir la página de ofrendas y copiar el IBAN.',
    bankDetails: 'Datos de pago',
    name: 'Nombre',
    copyIban: 'Copiar IBAN',
    ibanCopied: 'IBAN copiado',
    publicOfferingSubtitle:
        'Copia el IBAN y haz la transferencia en la app del banco.',
    iban: 'IBAN',
    bank: 'Banco',
    description: 'Descripción',
    offeringQrNote:
        'Nota: este QR abre una página sencilla del sitio con el IBAN para copiar. Después, haz la transferencia en tu app bancaria.',
    configureOfferingQr:
        'Configura offeringPageUrl en lib/content/offering.dart para activar el QR.',
  );

  static const german = AppStrings(
    sundayService: 'Sonntagsgottesdienst',
    homeSubtitle: 'Texte und Lieder für die FFPMU Portugal Gemeinde',
    appLanguage: 'App-Sprache',
    songs: 'Lieder',
    songsSubtitle: 'Texte, Seiten und verfügbare Audios',
    familyPromise: 'Familiengelöbnis',
    familyPromiseSubtitle: 'Lesung, Verlauf und Stimme',
    promiseHistoryLabel: 'Gelöbnis',
    motto: 'Motto 2026',
    mottoSubtitle: 'Jahrestext zum Lesen und Projizieren',
    offerings: 'Spenden / Zehnten',
    offeringsSubtitle: 'Kopierbare IBAN und QR fürs Telefon',
    weeklyVideos: 'Videos / Wochennews',
    weeklyVideosSubtitle: 'Aktuelle wöchentliche Videos von YouTube und Vimeo',
    copyVideoLink: 'Videolink kopieren',
    videoLinkCopied: 'Videolink kopiert',
    updateVideoLinks: 'Videolinks aktualisieren',
    updateVideoLinksSubtitle: 'Neue YouTube- und Vimeo-Links einfügen',
    youtubeVideoLink: 'YouTube-Link',
    vimeoVideoLink: 'Vimeo-Link',
    saveVideoLinks: 'Links speichern',
    videoLinksSaved: 'Videolinks gespeichert',
    videoLinksSavedLocally:
        'Links nur auf diesem Gerät gespeichert. Firestore-Regeln prüfen.',
    invalidVideoLink: 'YouTube- und Vimeo-Links prüfen',
    adminLogin: 'Administrator-Anmeldung',
    adminEmail: 'Administrator-E-Mail',
    password: 'Passwort',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    cancel: 'Abbrechen',
    togglePasswordVisibility: 'Passwort anzeigen oder ausblenden',
    adminAccessDenied: 'Dieses Konto hat keinen Administratorzugriff',
    signInFailed: 'Anmeldung fehlgeschlagen. E-Mail und Passwort prüfen.',
    adminArea: 'Administration',
    adminDashboard: 'Inhaltsverwaltung',
    countrySettings: 'Ländereinstellungen',
    countrySettingsSubtitle: 'Name, Sprache, Zeitzone und Status von Portugal',
    countryCode: 'Ländercode',
    countryName: 'Ländername',
    defaultLanguage: 'Standardsprache',
    timezone: 'Zeitzone',
    countryEnabled: 'Land aktiv',
    save: 'Speichern',
    countrySaved: 'Ländereinstellungen gespeichert',
    countrySaveFailed: 'Speichern in Firestore nicht möglich',
    searchSongHint: 'Lied suchen',
    clearSearch: 'Suche löschen',
    searchByTitlePageLyrics: 'Titel, Seite oder Text',
    all: 'Alle',
    withMusic: 'Mit Musik',
    noSongsFound: 'Keine Lieder gefunden',
    page: 'Seite',
    songCountSuffix: 'Lieder',
    holySongs: 'Heilige Lieder',
    convivialSongs: 'Gemeinschaftslieder',
    englishSongs: 'Englische Lieder',
    worshipSongs: 'Lobpreislieder',
    internationalSongs: 'Internationale Lieder',
    audioAvailable: 'Audio verfügbar',
    previousLyric: 'Vorherige Strophe',
    nextLyric: 'Nächste Strophe',
    increaseTextSize: 'Text vergrößern',
    decreaseTextSize: 'Text verkleinern',
    verse: 'Strophe',
    markAsUsed: 'Als verwendet markieren',
    resetHistory: 'Verlauf löschen',
    readAloud: 'Laut vorlesen',
    stopReading: 'Lesung stoppen',
    offeringTransfer: 'Banküberweisung',
    paymentQr: 'Zahlungs-QR',
    paymentQrInstruction:
        'Scannen, um die Spendenseite zu öffnen und die IBAN zu kopieren.',
    bankDetails: 'Zahlungsdaten',
    name: 'Name',
    copyIban: 'IBAN kopieren',
    ibanCopied: 'IBAN kopiert',
    publicOfferingSubtitle:
        'IBAN kopieren und die Überweisung in der Banking-App ausführen.',
    iban: 'IBAN',
    bank: 'Bank',
    description: 'Beschreibung',
    offeringQrNote:
        'Hinweis: Dieser QR öffnet eine einfache Website-Seite mit der IBAN zum Kopieren. Danach die Überweisung in der Banking-App ausführen.',
    configureOfferingQr:
        'Konfiguriere offeringPageUrl in lib/content/offering.dart, um den QR zu aktivieren.',
  );

  static const italian = AppStrings(
    sundayService: 'Servizio domenicale',
    homeSubtitle: 'Testi e canti per la comunità FFPMU Portugal',
    appLanguage: 'Lingua dell’app',
    songs: 'Canti',
    songsSubtitle: 'Testi, pagine e audio disponibile',
    familyPromise: 'Promessa della Famiglia',
    familyPromiseSubtitle: 'Lettura, cronologia e voce',
    promiseHistoryLabel: 'Promessa',
    motto: 'Motto 2026',
    mottoSubtitle: 'Testo annuale da leggere e proiettare',
    offerings: 'Offerte / Decime',
    offeringsSubtitle: 'IBAN copiabile e QR per il telefono',
    weeklyVideos: 'Video / Settimanale',
    weeklyVideosSubtitle: 'Ultimi video settimanali da YouTube e Vimeo',
    copyVideoLink: 'Copia link video',
    videoLinkCopied: 'Link video copiato',
    updateVideoLinks: 'Aggiorna link video',
    updateVideoLinksSubtitle: 'Incolla i nuovi link di YouTube e Vimeo',
    youtubeVideoLink: 'Link YouTube',
    vimeoVideoLink: 'Link Vimeo',
    saveVideoLinks: 'Salva link',
    videoLinksSaved: 'Link video salvati',
    videoLinksSavedLocally:
        'Link salvati solo su questo dispositivo. Controlla le regole Firestore.',
    invalidVideoLink: 'Controlla i link di YouTube e Vimeo',
    adminLogin: 'Accesso amministratore',
    adminEmail: 'Email amministratore',
    password: 'Password',
    signIn: 'Accedi',
    signOut: 'Esci',
    cancel: 'Annulla',
    togglePasswordVisibility: 'Mostra o nascondi password',
    adminAccessDenied: 'Questo account non ha accesso amministratore',
    signInFailed: 'Accesso non riuscito. Controlla email e password.',
    adminArea: 'Amministrazione',
    adminDashboard: 'Gestione contenuti',
    countrySettings: 'Impostazioni paese',
    countrySettingsSubtitle: 'Nome, lingua, fuso orario e stato del Portogallo',
    countryCode: 'Codice paese',
    countryName: 'Nome paese',
    defaultLanguage: 'Lingua predefinita',
    timezone: 'Fuso orario',
    countryEnabled: 'Paese attivo',
    save: 'Salva',
    countrySaved: 'Impostazioni paese salvate',
    countrySaveFailed: 'Impossibile salvare in Firestore',
    searchSongHint: 'Cerca un canto',
    clearSearch: 'Cancella ricerca',
    searchByTitlePageLyrics: 'Titolo, pagina o testo',
    all: 'Tutti',
    withMusic: 'Con musica',
    noSongsFound: 'Nessun canto trovato',
    page: 'Pagina',
    songCountSuffix: 'canti',
    holySongs: 'Canti sacri',
    convivialSongs: 'Canti di comunione',
    englishSongs: 'Canti in inglese',
    worshipSongs: 'Canti di adorazione',
    internationalSongs: 'Canti internazionali',
    audioAvailable: 'Audio disponibile',
    previousLyric: 'Strofa precedente',
    nextLyric: 'Strofa successiva',
    increaseTextSize: 'Aumenta testo',
    decreaseTextSize: 'Riduci testo',
    verse: 'Strofa',
    markAsUsed: 'Segna come usata',
    resetHistory: 'Cancella cronologia',
    readAloud: 'Leggi ad alta voce',
    stopReading: 'Ferma lettura',
    offeringTransfer: 'Bonifico bancario',
    paymentQr: 'QR per pagamento',
    paymentQrInstruction:
        'Scansiona per aprire la pagina delle offerte e copiare l’IBAN.',
    bankDetails: 'Dati di pagamento',
    name: 'Nome',
    copyIban: 'Copia IBAN',
    ibanCopied: 'IBAN copiato',
    publicOfferingSubtitle: 'Copia l’IBAN e fai il bonifico nell’app bancaria.',
    iban: 'IBAN',
    bank: 'Banca',
    description: 'Descrizione',
    offeringQrNote:
        'Nota: questo QR apre una pagina semplice del sito con l’IBAN da copiare. Poi fai il bonifico nella tua app bancaria.',
    configureOfferingQr:
        'Configura offeringPageUrl in lib/content/offering.dart per attivare il QR.',
  );

  static const french = AppStrings(
    sundayService: 'Service du dimanche',
    homeSubtitle: 'Textes et chants pour la communauté FFPMU Portugal',
    appLanguage: 'Langue de l’app',
    songs: 'Chants',
    songsSubtitle: 'Paroles, pages et audio disponible',
    familyPromise: 'Promesse de la Famille',
    familyPromiseSubtitle: 'Lecture, historique et voix',
    promiseHistoryLabel: 'Promesse',
    motto: 'Devise 2026',
    mottoSubtitle: 'Texte annuel à lire et projeter',
    offerings: 'Offrandes / Dîmes',
    offeringsSubtitle: 'IBAN copiable et QR pour téléphone',
    weeklyVideos: 'Vidéos / Hebdo',
    weeklyVideosSubtitle: 'Dernières vidéos hebdomadaires de YouTube et Vimeo',
    copyVideoLink: 'Copier le lien vidéo',
    videoLinkCopied: 'Lien vidéo copié',
    updateVideoLinks: 'Mettre à jour les liens vidéo',
    updateVideoLinksSubtitle: 'Collez les nouveaux liens YouTube et Vimeo',
    youtubeVideoLink: 'Lien YouTube',
    vimeoVideoLink: 'Lien Vimeo',
    saveVideoLinks: 'Enregistrer les liens',
    videoLinksSaved: 'Liens vidéo enregistrés',
    videoLinksSavedLocally:
        'Liens enregistrés uniquement sur cet appareil. Vérifiez les règles Firestore.',
    invalidVideoLink: 'Vérifiez les liens YouTube et Vimeo',
    adminLogin: 'Connexion administrateur',
    adminEmail: 'Email administrateur',
    password: 'Mot de passe',
    signIn: 'Se connecter',
    signOut: 'Se déconnecter',
    cancel: 'Annuler',
    togglePasswordVisibility: 'Afficher ou masquer le mot de passe',
    adminAccessDenied: 'Ce compte ne dispose pas d’un accès administrateur',
    signInFailed: 'Connexion impossible. Vérifiez l’email et le mot de passe.',
    adminArea: 'Administration',
    adminDashboard: 'Gestion du contenu',
    countrySettings: 'Paramètres du pays',
    countrySettingsSubtitle:
        'Nom, langue, fuseau horaire et statut du Portugal',
    countryCode: 'Code du pays',
    countryName: 'Nom du pays',
    defaultLanguage: 'Langue par défaut',
    timezone: 'Fuseau horaire',
    countryEnabled: 'Pays actif',
    save: 'Enregistrer',
    countrySaved: 'Paramètres du pays enregistrés',
    countrySaveFailed: 'Impossible d’enregistrer dans Firestore',
    searchSongHint: 'Rechercher un chant',
    clearSearch: 'Effacer la recherche',
    searchByTitlePageLyrics: 'Titre, page ou paroles',
    all: 'Tous',
    withMusic: 'Avec musique',
    noSongsFound: 'Aucun chant trouvé',
    page: 'Page',
    songCountSuffix: 'chants',
    holySongs: 'Chants sacrés',
    convivialSongs: 'Chants de convivialité',
    englishSongs: 'Chants en anglais',
    worshipSongs: 'Chants de louange',
    internationalSongs: 'Chants internationaux',
    audioAvailable: 'Audio disponible',
    previousLyric: 'Couplet précédent',
    nextLyric: 'Couplet suivant',
    increaseTextSize: 'Agrandir le texte',
    decreaseTextSize: 'Réduire le texte',
    verse: 'Couplet',
    markAsUsed: 'Marquer comme utilisée',
    resetHistory: 'Effacer l’historique',
    readAloud: 'Lire à voix haute',
    stopReading: 'Arrêter la lecture',
    offeringTransfer: 'Virement bancaire',
    paymentQr: 'QR de paiement',
    paymentQrInstruction:
        'Scannez pour ouvrir la page d’offrandes et copier l’IBAN.',
    bankDetails: 'Détails du paiement',
    name: 'Nom',
    copyIban: 'Copier IBAN',
    ibanCopied: 'IBAN copié',
    publicOfferingSubtitle:
        'Copiez l’IBAN puis faites le virement dans votre app bancaire.',
    iban: 'IBAN',
    bank: 'Banque',
    description: 'Description',
    offeringQrNote:
        'Remarque : ce QR ouvre une page simple du site avec l’IBAN à copier. Faites ensuite le virement dans votre app bancaire.',
    configureOfferingQr:
        'Configurez offeringPageUrl dans lib/content/offering.dart pour activer le QR.',
  );
}
