import 'package:ffpmupt/settings/app_language.dart';

enum P0Text {
  sundayActions,
  resources,
  startSunday,
  sundayMode,
  sundayModeSubtitle,
  prepare,
  activeService,
  configureSequence,
  fullscreen,
  open,
  done,
  finish,
  offlineTitle,
  offlineReady,
  offlinePartial,
  offlineAvailable,
  offlinePreparing,
  downloadOffline,
  retry,
  internetVideo,
  validationTitle,
  validationSubtitle,
  reportsProgress,
  noPaperMetric,
  noInterruptionsMetric,
  averageRating,
  feedbackTitle,
  withoutPaperQuestion,
  uninterruptedQuestion,
  ratingLabel,
  notesLabel,
  save,
  cancel,
  checklistTitle,
  checklistSubtitle,
  refresh,
  ready,
  needsAttention,
  countryActive,
  adminAccess,
  songs,
  promise,
  payments,
  videos,
  holyGrounds,
  offline,
  issues,
  noIssues,
  loadFailed,
  tryAgain,
  emptyHolyGroundsTitle,
  emptyHolyGroundsDescription,
  adminContent,
  adminCountry,
  adminOperations,
  optional,
}

class P0Strings {
  const P0Strings._(this._values);

  final Map<P0Text, String> _values;

  String operator [](P0Text key) => _values[key] ?? _english[key] ?? key.name;

  static P0Strings of(AppLanguage language) {
    return P0Strings._(switch (language) {
      AppLanguage.portuguese || AppLanguage.brazilian => _portuguese,
      AppLanguage.spanish => _spanish,
      AppLanguage.german => _german,
      AppLanguage.italian => _italian,
      AppLanguage.french => _french,
      AppLanguage.korean => _korean,
      AppLanguage.english => _english,
    });
  }
}

const _portuguese = <P0Text, String>{
  P0Text.sundayActions: 'Serviço de Domingo',
  P0Text.resources: 'Outros recursos',
  P0Text.startSunday: 'Iniciar Modo Domingo',
  P0Text.sundayMode: 'Modo Domingo',
  P0Text.sundayModeSubtitle:
      'Prepare, conduza e avalie o serviço num só lugar.',
  P0Text.prepare: 'Preparar serviço',
  P0Text.activeService: 'Serviço em andamento',
  P0Text.configureSequence: 'Configure a ordem e os conteúdos usados hoje.',
  P0Text.fullscreen: 'Tela cheia',
  P0Text.open: 'Abrir',
  P0Text.done: 'Concluído',
  P0Text.finish: 'Concluir serviço',
  P0Text.offlineTitle: 'Preparação offline',
  P0Text.offlineReady: 'Áudios prontos para uso offline',
  P0Text.offlinePartial: 'Alguns áudios ainda precisam de internet',
  P0Text.offlineAvailable: 'Os áudios só serão baixados quando confirmar.',
  P0Text.offlinePreparing: 'A preparar os áudios offline',
  P0Text.downloadOffline: 'Preparar áudios offline',
  P0Text.retry: 'Tentar novamente',
  P0Text.internetVideo: 'Os vídeos continuam a precisar de internet.',
  P0Text.validationTitle: 'Validação em domingos reais',
  P0Text.validationSubtitle: 'Registe 3 serviços para validar o fluxo.',
  P0Text.reportsProgress: 'domingos registados',
  P0Text.noPaperMetric: 'Sem papel',
  P0Text.noInterruptionsMetric: 'Sem interrupções',
  P0Text.averageRating: 'Avaliação média',
  P0Text.feedbackTitle: 'Como correu o serviço?',
  P0Text.withoutPaperQuestion: 'O serviço foi concluído sem papel?',
  P0Text.uninterruptedQuestion: 'O app funcionou sem interrupções?',
  P0Text.ratingLabel: 'Avaliação',
  P0Text.notesLabel: 'Notas (opcional)',
  P0Text.save: 'Guardar',
  P0Text.cancel: 'Cancelar',
  P0Text.checklistTitle: 'Prontidão do país',
  P0Text.checklistSubtitle: 'Confirme o conteúdo antes do lançamento.',
  P0Text.refresh: 'Atualizar',
  P0Text.ready: 'Pronto para lançar',
  P0Text.needsAttention: 'Ainda precisa de atenção',
  P0Text.countryActive: 'País ativo',
  P0Text.adminAccess: 'Administrador com acesso',
  P0Text.songs: 'Músicas válidas',
  P0Text.promise: 'Promessa nos idiomas necessários',
  P0Text.payments: 'Pagamentos configurados',
  P0Text.videos: 'Vídeos semanais configurados',
  P0Text.holyGrounds: 'Holy Grounds publicados',
  P0Text.offline: 'Conteúdo offline preparado',
  P0Text.issues: 'Problemas encontrados',
  P0Text.noIssues: 'Nenhum problema de conteúdo encontrado.',
  P0Text.loadFailed: 'Não foi possível carregar os dados.',
  P0Text.tryAgain: 'Tentar novamente',
  P0Text.emptyHolyGroundsTitle: 'Nenhum local publicado ainda',
  P0Text.emptyHolyGroundsDescription:
      'Os Holy Grounds dos países disponíveis aparecerão aqui.',
  P0Text.adminContent: 'Conteúdo',
  P0Text.adminCountry: 'País',
  P0Text.adminOperations: 'Operações',
  P0Text.optional: 'opcional',
};

const _english = <P0Text, String>{
  P0Text.sundayActions: 'Sunday Service',
  P0Text.resources: 'Other resources',
  P0Text.startSunday: 'Start Sunday Mode',
  P0Text.sundayMode: 'Sunday Mode',
  P0Text.sundayModeSubtitle:
      'Prepare, run and evaluate the service in one place.',
  P0Text.prepare: 'Prepare service',
  P0Text.activeService: 'Service in progress',
  P0Text.configureSequence: 'Set the order and content used today.',
  P0Text.fullscreen: 'Full screen',
  P0Text.open: 'Open',
  P0Text.done: 'Done',
  P0Text.finish: 'Finish service',
  P0Text.offlineTitle: 'Offline preparation',
  P0Text.offlineReady: 'Audio ready for offline use',
  P0Text.offlinePartial: 'Some audio still requires internet',
  P0Text.offlineAvailable: 'Audio downloads only after you confirm.',
  P0Text.offlinePreparing: 'Preparing offline audio',
  P0Text.downloadOffline: 'Prepare offline audio',
  P0Text.retry: 'Try again',
  P0Text.internetVideo: 'Videos still require an internet connection.',
  P0Text.validationTitle: 'Real Sunday validation',
  P0Text.validationSubtitle: 'Record 3 services to validate the flow.',
  P0Text.reportsProgress: 'Sundays recorded',
  P0Text.noPaperMetric: 'Paperless',
  P0Text.noInterruptionsMetric: 'No interruptions',
  P0Text.averageRating: 'Average rating',
  P0Text.feedbackTitle: 'How did the service go?',
  P0Text.withoutPaperQuestion: 'Was the service completed without paper?',
  P0Text.uninterruptedQuestion: 'Did the app work without interruptions?',
  P0Text.ratingLabel: 'Rating',
  P0Text.notesLabel: 'Notes (optional)',
  P0Text.save: 'Save',
  P0Text.cancel: 'Cancel',
  P0Text.checklistTitle: 'Country readiness',
  P0Text.checklistSubtitle: 'Confirm the content before launch.',
  P0Text.refresh: 'Refresh',
  P0Text.ready: 'Ready to launch',
  P0Text.needsAttention: 'Still needs attention',
  P0Text.countryActive: 'Country active',
  P0Text.adminAccess: 'Administrator has access',
  P0Text.songs: 'Valid songs',
  P0Text.promise: 'Promise in required languages',
  P0Text.payments: 'Payments configured',
  P0Text.videos: 'Weekly videos configured',
  P0Text.holyGrounds: 'Holy Grounds published',
  P0Text.offline: 'Offline content prepared',
  P0Text.issues: 'Issues found',
  P0Text.noIssues: 'No content issues found.',
  P0Text.loadFailed: 'Could not load the data.',
  P0Text.tryAgain: 'Try again',
  P0Text.emptyHolyGroundsTitle: 'No places published yet',
  P0Text.emptyHolyGroundsDescription:
      'Holy Grounds from the available countries will appear here.',
  P0Text.adminContent: 'Content',
  P0Text.adminCountry: 'Country',
  P0Text.adminOperations: 'Operations',
  P0Text.optional: 'Optional',
};

const _spanish = <P0Text, String>{
  P0Text.sundayActions: 'Servicio del domingo',
  P0Text.resources: 'Otros recursos',
  P0Text.startSunday: 'Iniciar modo domingo',
  P0Text.sundayMode: 'Modo domingo',
  P0Text.sundayModeSubtitle:
      'Prepara, dirige y evalúa el servicio en un solo lugar.',
  P0Text.prepare: 'Preparar servicio',
  P0Text.activeService: 'Servicio en curso',
  P0Text.configureSequence: 'Configura el orden y el contenido de hoy.',
  P0Text.fullscreen: 'Pantalla completa',
  P0Text.open: 'Abrir',
  P0Text.done: 'Completado',
  P0Text.finish: 'Finalizar servicio',
  P0Text.offlineTitle: 'Preparación sin conexión',
  P0Text.offlineReady: 'Audios listos sin conexión',
  P0Text.offlinePartial: 'Algunos audios aún necesitan internet',
  P0Text.offlineAvailable: 'Los audios solo se descargan al confirmar.',
  P0Text.offlinePreparing: 'Preparando audios sin conexión',
  P0Text.downloadOffline: 'Preparar audios sin conexión',
  P0Text.retry: 'Reintentar',
  P0Text.internetVideo: 'Los vídeos siguen necesitando internet.',
  P0Text.validationTitle: 'Validación en domingos reales',
  P0Text.validationSubtitle: 'Registra 3 servicios para validar el flujo.',
  P0Text.reportsProgress: 'domingos registrados',
  P0Text.noPaperMetric: 'Sin papel',
  P0Text.noInterruptionsMetric: 'Sin interrupciones',
  P0Text.averageRating: 'Valoración media',
  P0Text.feedbackTitle: '¿Cómo fue el servicio?',
  P0Text.withoutPaperQuestion: '¿Se completó el servicio sin papel?',
  P0Text.uninterruptedQuestion: '¿La app funcionó sin interrupciones?',
  P0Text.ratingLabel: 'Valoración',
  P0Text.notesLabel: 'Notas (opcional)',
  P0Text.save: 'Guardar',
  P0Text.cancel: 'Cancelar',
  P0Text.checklistTitle: 'Preparación del país',
  P0Text.checklistSubtitle: 'Confirma el contenido antes del lanzamiento.',
  P0Text.refresh: 'Actualizar',
  P0Text.ready: 'Listo para lanzar',
  P0Text.needsAttention: 'Necesita atención',
  P0Text.countryActive: 'País activo',
  P0Text.adminAccess: 'Administrador con acceso',
  P0Text.songs: 'Canciones válidas',
  P0Text.promise: 'Promesa en los idiomas necesarios',
  P0Text.payments: 'Pagos configurados',
  P0Text.videos: 'Vídeos semanales configurados',
  P0Text.holyGrounds: 'Holy Grounds publicados',
  P0Text.offline: 'Contenido sin conexión preparado',
  P0Text.issues: 'Problemas encontrados',
  P0Text.noIssues: 'No se encontraron problemas de contenido.',
  P0Text.loadFailed: 'No se pudieron cargar los datos.',
  P0Text.tryAgain: 'Reintentar',
  P0Text.emptyHolyGroundsTitle: 'Aún no hay lugares publicados',
  P0Text.emptyHolyGroundsDescription:
      'Los Holy Grounds de los países disponibles aparecerán aquí.',
  P0Text.adminContent: 'Contenido',
  P0Text.adminCountry: 'País',
  P0Text.adminOperations: 'Operaciones',
  P0Text.optional: 'opcional',
};

const _german = <P0Text, String>{
  P0Text.sundayActions: 'Sonntagsgottesdienst',
  P0Text.resources: 'Weitere Inhalte',
  P0Text.startSunday: 'Sonntagsmodus starten',
  P0Text.sundayMode: 'Sonntagsmodus',
  P0Text.sundayModeSubtitle:
      'Gottesdienst an einem Ort vorbereiten, leiten und auswerten.',
  P0Text.prepare: 'Gottesdienst vorbereiten',
  P0Text.activeService: 'Gottesdienst läuft',
  P0Text.configureSequence: 'Reihenfolge und heutige Inhalte festlegen.',
  P0Text.fullscreen: 'Vollbild',
  P0Text.open: 'Öffnen',
  P0Text.done: 'Erledigt',
  P0Text.finish: 'Gottesdienst beenden',
  P0Text.offlineTitle: 'Offline-Vorbereitung',
  P0Text.offlineReady: 'Audio offline verfügbar',
  P0Text.offlinePartial: 'Einige Audios benötigen noch Internet',
  P0Text.offlineAvailable: 'Audio wird erst nach Bestätigung heruntergeladen.',
  P0Text.offlinePreparing: 'Offline-Audio wird vorbereitet',
  P0Text.downloadOffline: 'Offline-Audio vorbereiten',
  P0Text.retry: 'Erneut versuchen',
  P0Text.internetVideo: 'Videos benötigen weiterhin Internet.',
  P0Text.validationTitle: 'Validierung im echten Gottesdienst',
  P0Text.validationSubtitle: '3 Gottesdienste zur Validierung erfassen.',
  P0Text.reportsProgress: 'Sonntage erfasst',
  P0Text.noPaperMetric: 'Ohne Papier',
  P0Text.noInterruptionsMetric: 'Ohne Unterbrechung',
  P0Text.averageRating: 'Durchschnitt',
  P0Text.feedbackTitle: 'Wie lief der Gottesdienst?',
  P0Text.withoutPaperQuestion:
      'Wurde der Gottesdienst ohne Papier durchgeführt?',
  P0Text.uninterruptedQuestion: 'Funktionierte die App ohne Unterbrechung?',
  P0Text.ratingLabel: 'Bewertung',
  P0Text.notesLabel: 'Notizen (optional)',
  P0Text.save: 'Speichern',
  P0Text.cancel: 'Abbrechen',
  P0Text.checklistTitle: 'Länderbereitschaft',
  P0Text.checklistSubtitle: 'Inhalte vor dem Start prüfen.',
  P0Text.refresh: 'Aktualisieren',
  P0Text.ready: 'Startbereit',
  P0Text.needsAttention: 'Noch zu prüfen',
  P0Text.countryActive: 'Land aktiv',
  P0Text.adminAccess: 'Administrator hat Zugriff',
  P0Text.songs: 'Gültige Lieder',
  P0Text.promise: 'Versprechen in erforderlichen Sprachen',
  P0Text.payments: 'Zahlungen eingerichtet',
  P0Text.videos: 'Wöchentliche Videos eingerichtet',
  P0Text.holyGrounds: 'Holy Grounds veröffentlicht',
  P0Text.offline: 'Offline-Inhalte vorbereitet',
  P0Text.issues: 'Gefundene Probleme',
  P0Text.noIssues: 'Keine Inhaltsprobleme gefunden.',
  P0Text.loadFailed: 'Daten konnten nicht geladen werden.',
  P0Text.tryAgain: 'Erneut versuchen',
  P0Text.emptyHolyGroundsTitle: 'Noch keine Orte veröffentlicht',
  P0Text.emptyHolyGroundsDescription:
      'Holy Grounds der verfügbaren Länder erscheinen hier.',
  P0Text.adminContent: 'Inhalte',
  P0Text.adminCountry: 'Land',
  P0Text.adminOperations: 'Betrieb',
  P0Text.optional: 'freiwillig',
};

const _italian = <P0Text, String>{
  P0Text.sundayActions: 'Servizio domenicale',
  P0Text.resources: 'Altre risorse',
  P0Text.startSunday: 'Avvia modalità domenica',
  P0Text.sundayMode: 'Modalità domenica',
  P0Text.sundayModeSubtitle:
      'Prepara, conduci e valuta il servizio in un unico luogo.',
  P0Text.prepare: 'Prepara il servizio',
  P0Text.activeService: 'Servizio in corso',
  P0Text.configureSequence: 'Configura ordine e contenuti di oggi.',
  P0Text.fullscreen: 'Schermo intero',
  P0Text.open: 'Apri',
  P0Text.done: 'Completato',
  P0Text.finish: 'Concludi servizio',
  P0Text.offlineTitle: 'Preparazione offline',
  P0Text.offlineReady: 'Audio pronti offline',
  P0Text.offlinePartial: 'Alcuni audio richiedono ancora internet',
  P0Text.offlineAvailable: 'Gli audio si scaricano solo dopo la conferma.',
  P0Text.offlinePreparing: 'Preparazione audio offline',
  P0Text.downloadOffline: 'Prepara audio offline',
  P0Text.retry: 'Riprova',
  P0Text.internetVideo: 'I video richiedono ancora internet.',
  P0Text.validationTitle: 'Validazione nelle domeniche reali',
  P0Text.validationSubtitle: 'Registra 3 servizi per validare il flusso.',
  P0Text.reportsProgress: 'domeniche registrate',
  P0Text.noPaperMetric: 'Senza carta',
  P0Text.noInterruptionsMetric: 'Senza interruzioni',
  P0Text.averageRating: 'Valutazione media',
  P0Text.feedbackTitle: 'Com’è andato il servizio?',
  P0Text.withoutPaperQuestion: 'Il servizio è stato completato senza carta?',
  P0Text.uninterruptedQuestion: 'L’app ha funzionato senza interruzioni?',
  P0Text.ratingLabel: 'Valutazione',
  P0Text.notesLabel: 'Note (opzionale)',
  P0Text.save: 'Salva',
  P0Text.cancel: 'Annulla',
  P0Text.checklistTitle: 'Preparazione del paese',
  P0Text.checklistSubtitle: 'Conferma i contenuti prima del lancio.',
  P0Text.refresh: 'Aggiorna',
  P0Text.ready: 'Pronto al lancio',
  P0Text.needsAttention: 'Richiede attenzione',
  P0Text.countryActive: 'Paese attivo',
  P0Text.adminAccess: 'Amministratore con accesso',
  P0Text.songs: 'Canzoni valide',
  P0Text.promise: 'Promessa nelle lingue richieste',
  P0Text.payments: 'Pagamenti configurati',
  P0Text.videos: 'Video settimanali configurati',
  P0Text.holyGrounds: 'Holy Grounds pubblicati',
  P0Text.offline: 'Contenuti offline pronti',
  P0Text.issues: 'Problemi trovati',
  P0Text.noIssues: 'Nessun problema di contenuto trovato.',
  P0Text.loadFailed: 'Impossibile caricare i dati.',
  P0Text.tryAgain: 'Riprova',
  P0Text.emptyHolyGroundsTitle: 'Nessun luogo ancora pubblicato',
  P0Text.emptyHolyGroundsDescription:
      'Gli Holy Grounds dei paesi disponibili appariranno qui.',
  P0Text.adminContent: 'Contenuti',
  P0Text.adminCountry: 'Paese',
  P0Text.adminOperations: 'Operazioni',
  P0Text.optional: 'facoltativo',
};

const _french = <P0Text, String>{
  P0Text.sundayActions: 'Service du dimanche',
  P0Text.resources: 'Autres ressources',
  P0Text.startSunday: 'Démarrer le mode dimanche',
  P0Text.sundayMode: 'Mode dimanche',
  P0Text.sundayModeSubtitle:
      'Préparez, dirigez et évaluez le service au même endroit.',
  P0Text.prepare: 'Préparer le service',
  P0Text.activeService: 'Service en cours',
  P0Text.configureSequence: 'Configurez l’ordre et les contenus du jour.',
  P0Text.fullscreen: 'Plein écran',
  P0Text.open: 'Ouvrir',
  P0Text.done: 'Terminé',
  P0Text.finish: 'Terminer le service',
  P0Text.offlineTitle: 'Préparation hors ligne',
  P0Text.offlineReady: 'Audio prêt hors ligne',
  P0Text.offlinePartial: 'Certains audios nécessitent encore internet',
  P0Text.offlineAvailable: 'Les audios sont téléchargés après confirmation.',
  P0Text.offlinePreparing: 'Préparation des audios hors ligne',
  P0Text.downloadOffline: 'Préparer les audios hors ligne',
  P0Text.retry: 'Réessayer',
  P0Text.internetVideo: 'Les vidéos nécessitent toujours internet.',
  P0Text.validationTitle: 'Validation en conditions réelles',
  P0Text.validationSubtitle: 'Enregistrez 3 services pour valider le parcours.',
  P0Text.reportsProgress: 'dimanches enregistrés',
  P0Text.noPaperMetric: 'Sans papier',
  P0Text.noInterruptionsMetric: 'Sans interruption',
  P0Text.averageRating: 'Note moyenne',
  P0Text.feedbackTitle: 'Comment s’est passé le service ?',
  P0Text.withoutPaperQuestion: 'Le service a-t-il été réalisé sans papier ?',
  P0Text.uninterruptedQuestion: 'L’app a-t-elle fonctionné sans interruption ?',
  P0Text.ratingLabel: 'Note',
  P0Text.notesLabel: 'Notes (facultatif)',
  P0Text.save: 'Enregistrer',
  P0Text.cancel: 'Annuler',
  P0Text.checklistTitle: 'Préparation du pays',
  P0Text.checklistSubtitle: 'Vérifiez le contenu avant le lancement.',
  P0Text.refresh: 'Actualiser',
  P0Text.ready: 'Prêt à lancer',
  P0Text.needsAttention: 'Nécessite une attention',
  P0Text.countryActive: 'Pays actif',
  P0Text.adminAccess: 'Administrateur autorisé',
  P0Text.songs: 'Chants valides',
  P0Text.promise: 'Promesse dans les langues requises',
  P0Text.payments: 'Paiements configurés',
  P0Text.videos: 'Vidéos hebdomadaires configurées',
  P0Text.holyGrounds: 'Holy Grounds publiés',
  P0Text.offline: 'Contenu hors ligne préparé',
  P0Text.issues: 'Problèmes trouvés',
  P0Text.noIssues: 'Aucun problème de contenu détecté.',
  P0Text.loadFailed: 'Impossible de charger les données.',
  P0Text.tryAgain: 'Réessayer',
  P0Text.emptyHolyGroundsTitle: 'Aucun lieu publié pour le moment',
  P0Text.emptyHolyGroundsDescription:
      'Les Holy Grounds des pays disponibles apparaîtront ici.',
  P0Text.adminContent: 'Contenu',
  P0Text.adminCountry: 'Pays',
  P0Text.adminOperations: 'Opérations',
  P0Text.optional: 'facultatif',
};

const _korean = <P0Text, String>{
  P0Text.sundayActions: '주일 예배',
  P0Text.resources: '기타 자료',
  P0Text.startSunday: '주일 모드 시작',
  P0Text.sundayMode: '주일 모드',
  P0Text.sundayModeSubtitle: '한 곳에서 예배를 준비하고 진행하며 평가합니다.',
  P0Text.prepare: '예배 준비',
  P0Text.activeService: '예배 진행 중',
  P0Text.configureSequence: '오늘 사용할 순서와 콘텐츠를 설정하세요.',
  P0Text.fullscreen: '전체 화면',
  P0Text.open: '열기',
  P0Text.done: '완료',
  P0Text.finish: '예배 마치기',
  P0Text.offlineTitle: '오프라인 준비',
  P0Text.offlineReady: '오프라인 오디오 준비 완료',
  P0Text.offlinePartial: '일부 오디오는 인터넷이 필요합니다',
  P0Text.offlineAvailable: '확인한 후에만 오디오를 다운로드합니다.',
  P0Text.offlinePreparing: '오프라인 오디오 준비 중',
  P0Text.downloadOffline: '오프라인 오디오 준비',
  P0Text.retry: '다시 시도',
  P0Text.internetVideo: '영상은 인터넷 연결이 필요합니다.',
  P0Text.validationTitle: '실제 주일 예배 검증',
  P0Text.validationSubtitle: '3회의 예배를 기록해 흐름을 검증하세요.',
  P0Text.reportsProgress: '회 기록됨',
  P0Text.noPaperMetric: '종이 없이',
  P0Text.noInterruptionsMetric: '중단 없이',
  P0Text.averageRating: '평균 평가',
  P0Text.feedbackTitle: '예배는 어떠했나요?',
  P0Text.withoutPaperQuestion: '종이 없이 예배를 마쳤나요?',
  P0Text.uninterruptedQuestion: '앱이 중단 없이 작동했나요?',
  P0Text.ratingLabel: '평가',
  P0Text.notesLabel: '메모 (선택)',
  P0Text.save: '저장',
  P0Text.cancel: '취소',
  P0Text.checklistTitle: '국가 준비 상태',
  P0Text.checklistSubtitle: '출시 전에 콘텐츠를 확인하세요.',
  P0Text.refresh: '새로고침',
  P0Text.ready: '출시 준비 완료',
  P0Text.needsAttention: '확인 필요',
  P0Text.countryActive: '국가 활성화',
  P0Text.adminAccess: '관리자 접근 가능',
  P0Text.songs: '유효한 성가',
  P0Text.promise: '필수 언어의 가정맹세',
  P0Text.payments: '헌금 정보 설정됨',
  P0Text.videos: '주간 영상 설정됨',
  P0Text.holyGrounds: '성지 게시됨',
  P0Text.offline: '오프라인 콘텐츠 준비됨',
  P0Text.issues: '발견된 문제',
  P0Text.noIssues: '콘텐츠 문제가 없습니다.',
  P0Text.loadFailed: '데이터를 불러올 수 없습니다.',
  P0Text.tryAgain: '다시 시도',
  P0Text.emptyHolyGroundsTitle: '아직 게시된 장소가 없습니다',
  P0Text.emptyHolyGroundsDescription: '사용 가능한 국가의 성지가 여기에 표시됩니다.',
  P0Text.adminContent: '콘텐츠',
  P0Text.adminCountry: '국가',
  P0Text.adminOperations: '운영',
  P0Text.optional: '선택 사항',
};
